INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('11111','Miembro del Poder Ejecutivo nacional o departamental'),
	 ('11112','Miembro de los Cuerpos Legislativos nacionales o departamentales'),
	 ('11113','Ministro de Suprema Corte de Justicia, Tribunal de lo Contencioso Administrativo o Tribunal de Apelaciones'),
	 ('11121','Miembros de Corte Electoral, Juntas Electorales o Ministros del Tribunal de Cuentas'),
	 ('11200','Personal Directivo de la Administración Pública'),
	 ('11411','Dirigente o administrador de partido político'),
	 ('11421','Dirigente o administrador de organización de empleadores'),
	 ('11422','Dirigente o administrador de organización de trabajadores'),
	 ('11423','Dirigente o administrador de otra organización de interés socioeconómico'),
	 ('11431','Dirigente o administrador de organización humanitaria');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('11432','Dirigente o administrador de organización de protección de la fauna, de la naturaleza, ecologista o del medio ambiente'),
	 ('12101','Presidente o Director de empresa u Organización'),
	 ('12102','Gerente General de empresa u Organización'),
	 ('12201','Gerente de departamento de producción y operaciones'),
	 ('12311','Gerente de departamento financiero o administrativo'),
	 ('12321','Gerente de departamento de personal o de relaciones laborales'),
	 ('12331','Gerente de departamento de ventas o comercialización'),
	 ('12341','Gerente de departamento de publicidad o de relaciones públicas'),
	 ('12351','Gerente de departamento de compras, abastecimiento o distribución'),
	 ('12361','Gerente de departamento de informática');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('12371','Gerente de departamento en investigación y desarrollo'),
	 ('12391','Otros gerentes de departamentos n.c.b.o.e.'),
	 ('13101','Dueño o gerente de pequeña empresa'),
	 ('21111','Físico'),
	 ('21112','Astrónomo'),
	 ('21121','Meteorólogo o climatólogo'),
	 ('21131','Químico investigador'),
	 ('21141','Geólogo o geofísico'),
	 ('21142','Oceanógrafo'),
	 ('21143','Paleontólogo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('21211','Matemático o actuario'),
	 ('21221','Demógrafo'),
	 ('21222','Estadístico'),
	 ('21311','Analista de sistemas informáticos'),
	 ('21312','Ingeniero en sistemas informáticos'),
	 ('21321','Programador informático'),
	 ('21391','Profesionales de la informática n.c.b.o.e.'),
	 ('21411','Arquitecto de edificios'),
	 ('21412','Arquitecto paisajista'),
	 ('21413','Planificador de tránsito o urbanista');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('21421','Ingeniero civil'),
	 ('21431','Ingeniero electricista'),
	 ('21441','Ingeniero electrónico'),
	 ('21442','Ingeniero de telecomunicaciones'),
	 ('21451','Ingeniero mecánico'),
	 ('21452','Ingeniero mecánico en construcción naval'),
	 ('21461','Ingeniero químico o químico industrial'),
	 ('21471','Ingeniero metalúrgico o en minería'),
	 ('21481','Agrimensor o ingeniero agrimensor'),
	 ('21482','Cartógrafo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('21483','Topógrafo'),
	 ('21484','Fotogrametrista'),
	 ('21491','Ingeniero industrial'),
	 ('21492','Ingeniero en organización y métodos'),
	 ('21499','Arquitectos, ingenieros y afines n.c.b.o.e.'),
	 ('22111','Biólogo'),
	 ('22112','Botánico'),
	 ('22113','Zoólogo'),
	 ('22119','Ecólogo'),
	 ('22121','Farmacólogo, biofísico o bioquímico');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('22122','Patólogo'),
	 ('22131','Ingeniero agrónomo agrícola-ganadero'),
	 ('22132','Ingeniero agrónomo granjero'),
	 ('22133','Ingeniero agrónomo forestal'),
	 ('22139','Ingeniero agrónomo n.c.b.o.e.'),
	 ('22211','Médico en medicina general'),
	 ('22212','Médico especialista'),
	 ('22221','Odontólogo'),
	 ('22222','Odontólogo especialista'),
	 ('22231','Veterinario');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('22241','Químico farmacéutico'),
	 ('22291','Médicos y profesionales afines (excepto el personal de enfermería y partería), n.c.b.o.e.'),
	 ('22300','Nurse jefe'),
	 ('22301','Nurse'),
	 ('22302','Partera'),
	 ('23111','Profesor universitario de ciencias físicas y químicas'),
	 ('23112','Profesor universitario de ingeniería y arquitectura'),
	 ('23113','Profesor universitario de ciencias biológicas y médicas'),
	 ('23114','Profesor universitario de ciencias exactas'),
	 ('23115','Profesor universitario de ciencias económicas y comerciales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('23116','Profesor universitario de derecho'),
	 ('23117','Profesor universitario de ciencias agronómicas'),
	 ('23118','Profesor universitario de ciencias sociales'),
	 ('23119','Profesor universitario n.c.b.o.e.'),
	 ('23121','Profesor de enseñanza superior en artes industriales'),
	 ('23122','Profesor de enseñanza superior en tecnología, electricidad, electrónica o construcción'),
	 ('23123','Profesor de enseñanza superior en bellas artes'),
	 ('23124','Profesor de enseñanza superior en ciencias militares'),
	 ('23129','Profesor de enseñanza superior n.c.b.o.e.'),
	 ('23211','Profesor de enseñanza secundaria en idioma español o literatura');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('23212','Profesor de enseñanza secundaria en ciencias exactas o naturales'),
	 ('23213','Profesor de enseñanza secundaria en ciencias biológicas'),
	 ('23214','Profesor de enseñanza secundaria en lenguas extranjeras'),
	 ('23215','Profesor de enseñanza secundaria en ciencias sociales'),
	 ('23216','Profesor de enseñanza secundaria en bellas artes'),
	 ('23217','Profesor de enseñanza secundaria en contabilidad, comercio y secretariado'),
	 ('23218','Profesor de enseñanza secundaria en ciencias agrícolas'),
	 ('23221','Profesor de enseñanza secundaria en artes industriales o tecnologías'),
	 ('23222','Profesor de enseñanza secundaria en informática'),
	 ('23223','Profesor de enseñanza secundaria en educación física');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('23229','Profesor de enseñanza secundaria n.c.b.o.e.'),
	 ('23311','Maestro titulado de la enseñanza primaria'),
	 ('23321','Maestro titulado de la enseñanza preescolar'),
	 ('23401','Maestro especializado en enseñanza para ciegos'),
	 ('23402','Maestro especializado en enseñanza para sordos o mudos'),
	 ('23403','Maestro especializado en enseñanza para deficientes mentales'),
	 ('23404','Maestro especializado en enseñanza correctiva'),
	 ('23511','Especialista en métodos pedagógicos o en material didáctico'),
	 ('23521','Inspector de la enseñanza secundaria'),
	 ('23522','Inspector de la enseñanza primaria');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('23591','Profesores de idiomas extranjeros'),
	 ('23592','Profesor de taquigrafía o dactilografía'),
	 ('23593','Profesor de instrumentos musicales'),
	 ('23594','Profesor de canto o solfeo'),
	 ('23595','Maestra de ballet'),
	 ('23599','Otro profesional de la enseñanza n.c.b.o.e.'),
	 ('24111','Contador público'),
	 ('24112','Auditor contable'),
	 ('24113','Perito contable'),
	 ('24121','Analista ocupacional');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24122','Consejero en orientación profesional'),
	 ('24123','Conciliador laboral'),
	 ('24124','Especialista en relaciones profesionales'),
	 ('24125','Especialista en seguridad en el trabajo'),
	 ('24191','Licenciado en administración'),
	 ('24192','Técnico en administración o administrador de empresas'),
	 ('24193','Analista financiero'),
	 ('24194','Analista de mercados (marketing)'),
	 ('24195','Agente de marcas y patentes'),
	 ('24196','Especialista en relaciones públicas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24197','Publicista responsable de campaña publicitaria'),
	 ('24198','Licenciado en relaciones internacionales'),
	 ('24199','Especialistas en organización y administración de empresas y afines n.c.b.o.e.'),
	 ('24211','Abogado'),
	 ('24212','Fiscal'),
	 ('24221','Juez Letrado de Primera Instancia'),
	 ('24222','Juez de Paz'),
	 ('24223','Magistrado del Tribunal de Faltas'),
	 ('24291','Escribano público o notario'),
	 ('24292','Procurador');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24293','Actuario de Juzgado o Tribunal'),
	 ('24299','Profesionales del derecho n.c.b.o.e.'),
	 ('24311','Archivero'),
	 ('24312','Conservador de museo'),
	 ('24321','Bibliotecario o bibliotecólogo'),
	 ('24322','Documentalista o catalogador de biblioteca'),
	 ('24411','Economista'),
	 ('24412','Econometrista'),
	 ('24421','Antropólogo'),
	 ('24422','Sociólogo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24423','Geógrafo'),
	 ('24424','Arqueólogo'),
	 ('24425','Especialista en ciencias de la comunicación'),
	 ('24426','Criminólogo'),
	 ('24431','Filósofo'),
	 ('24432','Historiador'),
	 ('24433','Politólogo o especialista en ciencia política'),
	 ('24434','Genealogista'),
	 ('24441','Filólogo'),
	 ('24442','Traductor público');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24443','Intérprete de idiomas'),
	 ('24444','Grafólogo'),
	 ('24445','Especialista en semántica o semiólogo'),
	 ('24451','Psicólogo'),
	 ('24452','Psicoterapeuta'),
	 ('24461','Asistente social'),
	 ('24510','Redactor jefe de diarios o revistas'),
	 ('24511','Escritor, libretista o autor'),
	 ('24512','Periodista'),
	 ('24513','Reportero o cronista');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24514','Redactor'),
	 ('24515','Secretario de redacción'),
	 ('24516','Crítico de cine, teatro, radio y T.V.'),
	 ('24517','Comentarista'),
	 ('24518','Corresponsal de medios de información'),
	 ('24519','Editor de libros'),
	 ('24521','Escultor'),
	 ('24522','Pintor artístico'),
	 ('24523','Dibujante publicitario'),
	 ('24524','Dibujante proyectista en artes gráficas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24525','Dibujante caricaturista y de dibujos animados'),
	 ('24526','Restaurador de cuadros y obras de arte'),
	 ('24527','Dibujante de modelos de joyería y orfebrería'),
	 ('24528','Maquetista'),
	 ('24529','Artista creativo'),
	 ('24531','Compositor'),
	 ('24532','Cantante concertista'),
	 ('24533','Cantante de música popular'),
	 ('24534','Músico instrumentista de concierto'),
	 ('24535','Músico instrumentista popular');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('24541','Coreógrafo'),
	 ('24542','Bailarín de danza clásica y moderna'),
	 ('24550','Director de escena en cine o teatro'),
	 ('24551','Actor'),
	 ('24552','Payador o recitador'),
	 ('24601','Obispo, arzobispo, sacerdote o párroco'),
	 ('24602','Rabino'),
	 ('24603','Monje o monja'),
	 ('24604','Pastor protestante'),
	 ('24605','Pae espiritual');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31111','Técnico físico'),
	 ('31112','Técnico meteorólogo o en climatología'),
	 ('31113','Técnico en geología'),
	 ('31114','Técnico químico'),
	 ('31121','Técnico agrimensor'),
	 ('31122','Técnico o calculista en ingeniería civil'),
	 ('31123','Sobrestante'),
	 ('31124','Inspector técnico en ingeniería civil'),
	 ('31131','Técnico electricista o electrotécnico'),
	 ('31141','Técnico electrónico');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31142','Técnico electrónico en material informático'),
	 ('31143','Técnico en telecomunicaciones (radio o radar)'),
	 ('31144','Técnico en telecomunicaciones (teléfono)'),
	 ('31145','Técnico en telecomunicaciones (televisión)'),
	 ('31151','Técnico mecánico en calefacción, refrigeración y ventilación'),
	 ('31152','Técnico mecánico en automóviles'),
	 ('31153','Técnico mecánico en motores'),
	 ('31154','Técnico mecánico en maquinaria y herramientas industriales'),
	 ('31155','Técnico mecánico en maquinaria y herramientas agrícolas'),
	 ('31156','Técnico mecánico en aeronáutica');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31157','Técnico mecánico en construcción naval'),
	 ('31159','Técnico mecánico n.c.b.o.e.'),
	 ('31161','Técnico en química industrial'),
	 ('31171','Técnico en minería'),
	 ('31172','Técnico metalúrgico'),
	 ('31181','Dibujante en arquitectura'),
	 ('34745','Domador o amaestrador de fieras'),
	 ('31182','Dibujante en ingeniería civil, eléctrica, mecánica o naval'),
	 ('31183','Dibujante en cartografía o topografía'),
	 ('31184','Dibujante en ilustraciones técnicas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31185','Dibujante en diseño industrial'),
	 ('31189','Dibujante n.c.b.o.e.'),
	 ('31191','Técnico en estudio de tiempos y movimientos'),
	 ('31192','Técnico en cálculo de costos y cantidades'),
	 ('31199','Técnicos industriales en ciencias físicas, químicas y de la ingeniería n.c.b.o.e.'),
	 ('31210','Técnico jefe en programación informática'),
	 ('31211','Técnico en análisis informático'),
	 ('31212','Técnico en programación informática'),
	 ('31213','Técnico en servicios informáticos para usuarios'),
	 ('31221','Operador PC o técnico en control de equipos informáticos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31222','Operador de equipos informáticos periféricos'),
	 ('31231','Técnico verificador de robots'),
	 ('31311','Fotógrafo retratista'),
	 ('31312','Fotógrafo aéreo'),
	 ('31313','Fotógrafo científico'),
	 ('31314','Fotógrafo publicitario'),
	 ('31315','Fotógrafo de microfilmación'),
	 ('31316','Fotógrafo de modas'),
	 ('31317','Fotógrafo de policía'),
	 ('31318','Fotógrafo de prensa o reportero gráfico');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31319','Fotógrafo n.c.b.o.e.'),
	 ('31321','Operador de equipo de sonorización de cine'),
	 ('31322','Operador de grabación de sonido en discos, en radio o en televisión'),
	 ('31323','Técnico de equipos de grabación en cinta magnética, en discos o en video'),
	 ('31324','Camarógrafo de televisión o de cine'),
	 ('31329','Operador de equipo de grabación de imagen y sonido'),
	 ('31331','Operador de estación emisora de radio o de televisión'),
	 ('31332','Operador de equipos móviles de radiodifusión o de televisión'),
	 ('31333','Operador de aparatos de estudio de radio o de televisión'),
	 ('31334','Operador de equipos de radiotelefonía');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31335','Operador de radio para navegación aérea o marítima'),
	 ('31336','Técnico de sala de control en radio o en televisión'),
	 ('31337','Operador de cabina de proyección cinematográfica'),
	 ('31339','Operador de equipos de radiodifusión, televisión o cine'),
	 ('31341','Operador de electrocardiografía'),
	 ('31342','Operador de electroencefalografía'),
	 ('31343','Operador de radiografía o rayos X'),
	 ('31349','Operador de aparatos de diagnóstico y tratamientos médicos'),
	 ('31391','Operadores de equipos ópticos y electrónicos n.c.b.o.e.'),
	 ('31410','Jefe de máquinas naval');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31411','Oficial maquinista naval'),
	 ('31420','Jefe de maniobras en puerto'),
	 ('31421','Capitán de barco de navegación marítima, fluvial o lacustre'),
	 ('31422','Marino mercante'),
	 ('31423','Patrón de barco o yate'),
	 ('31424','Oficial de navegación o de cubierta'),
	 ('31425','Capitán de puerto'),
	 ('31426','Práctico de puerto'),
	 ('31427','Práctico de río'),
	 ('31431','Comandante de aeronave');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31432','Piloto de aeronave'),
	 ('31433','Oficial navegante de aeronave'),
	 ('31434','Oficial mecánico de vuelo'),
	 ('31440','Jefe de torre de control en aeropuerto'),
	 ('31441','Controlador de tráfico aéreo'),
	 ('31451','Técnico en seguridad de tráfico aéreo'),
	 ('31511','Inspector de obras y edificios'),
	 ('31512','Inspector o investigador de incendios'),
	 ('31513','Técnico en prevención de incendios'),
	 ('31521','Inspector de seguridad y salud en trabajo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('31522','Inspector de seguridad y salud en protección de los consumidores, en medio ambiente o en establecimientos y fábricas'),
	 ('31523','Inspector en control de calidad de productos'),
	 ('31524','Inspector de vehículos'),
	 ('31525','Inspector en control de calidad de servicios'),
	 ('31526','Inspector de tránsito'),
	 ('31529','Inspector n.c.b.o.e.'),
	 ('32110','Jefe técnico en ciencias biológicas'),
	 ('32111','Técnico en bacteriología'),
	 ('32112','Técnico en hematología o en banco de sangre'),
	 ('32113','Técnico en biología, bioquímica o biofísica');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('32114','Técnico en anatomía o fisiología'),
	 ('32115','Técnico en farmacología'),
	 ('32116','Técnico en zoología o zootécnico'),
	 ('32117','Técnico en botánica'),
	 ('32118','Taxidermista'),
	 ('32119','Técnico de laboratorio'),
	 ('32121','Técnico agrónomo'),
	 ('32122','Técnico en arboricultura, floricultura u horticultura'),
	 ('32123','Técnico forestal o en silvicultura'),
	 ('32124','Técnico en riego');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('32131','Consejero agrícola o forestal'),
	 ('32141','Técnico en alimentos'),
	 ('32142','Técnico textil'),
	 ('32143','Técnico en cuero y calzado'),
	 ('32149','Técnico industrial en transformación de materias primas n.c.b.o.e.'),
	 ('32151','Técnico en control de calidad'),
	 ('32211','Asistente médico'),
	 ('32212','Practicante de medicina'),
	 ('32213','Instrumentista médico'),
	 ('32221','Higienista');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('32222','Inspector de sanidad'),
	 ('32231','Dietólogo o dietista'),
	 ('32232','Nutricionista'),
	 ('32241','Óptico o técnico en oftalmología'),
	 ('32251','Asistente de dentista'),
	 ('32252','Higienista dental'),
	 ('32261','Fisioterapeuta'),
	 ('32262','Terapeuta en readaptación física o profesional'),
	 ('32263','Quiropráctico'),
	 ('32264','Podólogo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('32265','Masajista o kinesiólogo'),
	 ('32266','Técnico en ortopedia y prótesis'),
	 ('32267','Técnico en gimnasia médica'),
	 ('32271','Asistente veterinario'),
	 ('32272','Técnico veterinario en inseminación artificial'),
	 ('32281','Asistente o auxiliar farmacéutico'),
	 ('32291','Técnico en homeopatía'),
	 ('34746','Titiritero o artista de marionetas'),
	 ('34747','Imitador'),
	 ('32299','Profesionales de nivel medio de la medicina moderna y la salud (excepto el personal de enfermería y partería) n.c.b.o.e.');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('32310','Enfermero jefe de nivel medio'),
	 ('32311','Enfermero de nivel medio'),
	 ('32321','Partera de nivel medio'),
	 ('32411','Curandero-naturista'),
	 ('32412','Herbolario'),
	 ('32413','Acupuntor'),
	 ('32421','Curandero religioso o por sugestión'),
	 ('33101','Maestro no titulado de la enseñanza primaria'),
	 ('33201','Maestro no titulado de educación preescolar o jardín de infantes'),
	 ('33301','Maestro no titulado de ciegos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('33302','Maestro no titulado de sordos o mudos'),
	 ('33303','Maestro no titulado de enseñanza correctiva'),
	 ('33304','Maestro no titulado de deficientes mentales'),
	 ('33401','Instructor de conducción de vehículos automotores'),
	 ('33402','Piloto instructor de vuelo'),
	 ('33403','Instructor de navegación a vela'),
	 ('34111','Agente de bolsa'),
	 ('34112','Agente de cambio'),
	 ('34113','Corredor de valores o de bolsa'),
	 ('34114','Asesor de inversiones');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34121','Asegurador, agente o corredor de seguros'),
	 ('34131','Agente inmobiliario o corredor de bienes raíces'),
	 ('34132','Administrador de propiedades inmuebles'),
	 ('34141','Agente de turismo o de viajes'),
	 ('34142','Organizador de viajes'),
	 ('34151','Agente de ventas'),
	 ('34152','Vendedor o corredor de plaza'),
	 ('34153','Viajante de comercio'),
	 ('34154','Representante de ventas'),
	 ('34155','Distribuidor');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34156','Visitador médico'),
	 ('34160','Jefe de compradores'),
	 ('34161','Comprador de mercaderías'),
	 ('34162','Comprador de servicios'),
	 ('34163','Comprador de mercaderías y suministros'),
	 ('34171','Rematador o martillero'),
	 ('34172','Tasador'),
	 ('34173','Tasador de seguros o siniestros'),
	 ('34191','Profesionales de nivel medio en operaciones financieras y comerciales, n.c.b.o.e.'),
	 ('34211','Agente de compras');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34212','Consignatario'),
	 ('34221','Despachante o declarante de aduana'),
	 ('34222','Agente marítimo'),
	 ('34231','Agente de oficina de colocación'),
	 ('34232','Funcionario de servicio de empleo'),
	 ('34291','Agente deportivo'),
	 ('34292','Agente de publicidad'),
	 ('34293','Agente musical, teatral o artístico'),
	 ('34294','Representante de servicios a empresas'),
	 ('34295','Agente literario');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34296','Gestor de trámites ante oficinas'),
	 ('34299','Agentes comerciales y corredores n.c.b.o.e.'),
	 ('34311','Secretario ejecutivo'),
	 ('34312','Taquígrafo de actas'),
	 ('34321','Auxiliar de bufete de abogado'),
	 ('34322','Auxiliar de escribanía o protocolista'),
	 ('34323','Alguacil de juzgado'),
	 ('34324','Empleado de seguros de nivel medio'),
	 ('34331','Tenedor de libros'),
	 ('34341','Auxiliar estadístico');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34342','Auxiliar matemático'),
	 ('34391','Funcionario o agente administrativo de consulado'),
	 ('34392','Secretario administrativo en la Administración Pública'),
	 ('34399','Profesionales de nivel medio de servicios de administración n.c.b.o.e.'),
	 ('34411','Aduanero, inspector o agente de aduana'),
	 ('34412','Inspector de inmigración'),
	 ('34413','Inspector de policía de frontera'),
	 ('34421','Recaudador de impuestos'),
	 ('34422','Funcionario del fisco'),
	 ('34423','Inspector de impuestos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34431','Funcionario de prestaciones de seguridad social'),
	 ('34432','Inspector de seguridad social'),
	 ('34441','Funcionario de expedición de pasaportes'),
	 ('34442','Funcionario de servicios de expedición de licencias y permisos'),
	 ('34443','Funcionario de inmigración'),
	 ('34444','Funcionario de permisos de construcción'),
	 ('34451','Inspector de control de precios'),
	 ('34452','Inspector de pesas y medidas'),
	 ('34453','Inspector de trabajo y salarios'),
	 ('34454','Funcionario técnico de los registros electorales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34455','Oficial del Registro de Estado Civil'),
	 ('34456','Funcionario técnico de los registros públicos'),
	 ('34459','Otros inspectores de la Administración Pública de nivel medio'),
	 ('34490','Jefe de departamento de la administración pública no oficinista'),
	 ('34499','Funcionario no oficinista de la administración pública de nivel medio'),
	 ('34501','Inspector de policía'),
	 ('34502','Agente o funcionario de policía en investigaciones'),
	 ('34503','Detective privado'),
	 ('34601','Trabajador social de nivel medio'),
	 ('34602','Visitador social de nivel medio');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34711','Decorador de vidrieras o escaparates'),
	 ('34712','Decorador de interiores o de exposiciones'),
	 ('34713','Diseñador o decorador de cine o teatro'),
	 ('34714','Diseñador o dibujante de modas'),
	 ('34715','Diseñador de joyas'),
	 ('34716','Diseñador de telas y tejidos'),
	 ('34717','Diseñador de muebles'),
	 ('34718','Dibujante de carteles'),
	 ('34719','Diseñador de productos industriales y comerciales'),
	 ('34721','Locutor de radio');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34722','Locutor de televisión'),
	 ('34723','Presentador animador de espectáculos públicos, radio o televisión'),
	 ('34724','Comentarista entrevistador de televisión'),
	 ('34725','Cronista o locutor de noticiarios'),
	 ('34731','Director de orquesta de baile'),
	 ('34732','Director de banda o grupo musical'),
	 ('34733','Músico o cantor ambulante'),
	 ('34734','Músico o cantor de cabaret'),
	 ('34735','Bailarín de baile popular'),
	 ('34736','Bailarín de cabaret');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34741','Acróbata, equilibrista o trapecista'),
	 ('34742','Hipnotizador o ilusionista'),
	 ('34743','Payaso o cómico de circo'),
	 ('34744','Prestidigitador o mago'),
	 ('34748','Ventrílocuo'),
	 ('34750','Director técnico deportivo'),
	 ('34751','Entrenador o ayudante deportivo o entrenador de educación física'),
	 ('34752','Piloto de carretas de automóviles'),
	 ('34753','Funcionario de organización deportiva'),
	 ('34754','Arbitro o juez deportivo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('34755','Jockey'),
	 ('34756','Futbolista'),
	 ('34757','Basquetbolista'),
	 ('34758','Ciclista'),
	 ('34759','Deportista n.c.b.o.e.'),
	 ('34801','Predicador'),
	 ('34802','Diácono'),
	 ('41111','Mecanógrafo'),
	 ('41112','Taquígrafo'),
	 ('41120','Jefe de operadores de máquinas de tratamiento de textos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41121','Operador de máquina con procesador de texto'),
	 ('41122','Teletipista de telex'),
	 ('41123','Operador de telégrafo, telegrafista o radiotelegrafista'),
	 ('41130','Jefe de digitadores u operadores de entrada de datos'),
	 ('41131','Digitador u operador de entrada de datos'),
	 ('41141','Operador de máquinas contables'),
	 ('41142','Operador de calculadora'),
	 ('41143','Operador de facturadora'),
	 ('41151','Secretario'),
	 ('41210','Jefe de empleados de contabilidad y cálculo de costos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41211','Empleado de contabilidad'),
	 ('41212','Empleado de teneduría de libros'),
	 ('41213','Empleado de cálculo de costos y presupuesto'),
	 ('41214','Empleado de caja'),
	 ('41215','Empleado en cálculo o pago de salarios, o liquidador de sueldos'),
	 ('41216','Empleado en cuentas corrientes y descuentos'),
	 ('41217','Empleado de facturación'),
	 ('41219','Auxiliar o ayudante contable'),
	 ('41220','Jefe de empleados de servicios estadísticos y financieros'),
	 ('41221','Empleado actuarial');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41222','Empleado en estadística'),
	 ('41223','Empleado de servicios financieros'),
	 ('41224','Empleado de registro de títulos, acciones u otros valores'),
	 ('41225','Empleado de bancos'),
	 ('41226','Empleado de bolsa'),
	 ('41227','Empleado de oficinas de impuestos'),
	 ('41310','Jefe de empleados de control de abastecimiento e inventario'),
	 ('41311','Empleado de servicio de almacenaje'),
	 ('41312','Empleado de recepción, embarque y expedición de mercadería'),
	 ('41313','Empleado de registro de existencias o inventario');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41314','Empleado de control de peso'),
	 ('41315','Empleado de depósito'),
	 ('41316','Empleado de movimiento de mercaderías'),
	 ('41321','Empleado de cálculo de materiales'),
	 ('41322','Empleado de planificación de la producción'),
	 ('41323','Empleado de abastecimiento de materiales'),
	 ('41330','Jefe de empleados de servicios de transporte ferroviario'),
	 ('41331','Controlador administrativo de transporte ferroviario'),
	 ('41332','Empleado de movimiento de trenes'),
	 ('41333','Empleado de despacho de ferrocarril');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41339','Empleado de transporte ferroviario'),
	 ('41340','Jefe de empleados de servicios de transporte por carretera'),
	 ('41341','Controlador administrativo de transporte por carretera'),
	 ('41342','Empleado de despacho de vehículos'),
	 ('41349','Empleado de operaciones de transporte por carretera'),
	 ('41350','Jefe de empleados de servicios de transporte aéreo'),
	 ('41351','Controlador administrativo de tráfico aéreo'),
	 ('41352','Empleado de expedición en transporte aéreo'),
	 ('41359','Empleado en operaciones de transporte aéreo'),
	 ('41360','Jefe de empleados de servicio de transporte marítimo o fluvial');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41361','Controlador administrativo en transporte marítimo'),
	 ('41362','Empleado de despacho en barcos o muelles'),
	 ('41369','Empleado en operaciones de transporte marítimo o fluvial'),
	 ('41410','Jefe de empleados de biblioteca'),
	 ('41411','Archivista o empleado de archivo'),
	 ('41412','Empleado o asistente de biblioteca'),
	 ('41413','Operador de fotocopiadora'),
	 ('41414','Operador de copiadora de planos'),
	 ('41420','Supervisor de correo o jefe de empleados de servicios de correos'),
	 ('41421','Cartero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41422','Clasificador de correspondencia'),
	 ('41423','Repartidor de telegramas o encomiendas'),
	 ('41429','Empleado de servicios de correo n.c.b.o.e.'),
	 ('41431','Codificador de datos'),
	 ('41432','Corrector de pruebas de imprenta'),
	 ('41433','Empleado de máquina franqueadora'),
	 ('41441','Escribiente público'),
	 ('41900','Jefe o encargado de oficinas administrativas'),
	 ('41901','Empleado de registro de personal'),
	 ('41902','Empleado de registro de guías y repertorios');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('41903','Empleado marcador de tiempo de trabajo'),
	 ('41909','Auxiliar administrativo u otro oficinista n.c.b.o.e.'),
	 ('42110','Jefe de cajeros o Encargado de contabilidad de caja'),
	 ('42111','Cajero de banco, casa bancaria o casa de cambio'),
	 ('42112','Cajero de mostrador o de oficina'),
	 ('42113','Boletero de espectáculos públicos'),
	 ('42119','Cajero n.c.b.o.e.'),
	 ('42121','Cambista'),
	 ('42122','Empleado de operaciones de cambio'),
	 ('42123','Empleado de ventanilla de correos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('42130','Jefe de receptores de apuestas o de sala de casinos'),
	 ('42131','Crupier de sala de juegos'),
	 ('42132','Empleado de agencia de loterías y quinielas'),
	 ('42133','Receptor o corredor de apuesta'),
	 ('42134','Quinielero'),
	 ('42141','Prestamista de dinero'),
	 ('42151','Cobrador de alquileres'),
	 ('42152','Cobrador de facturas o deudas'),
	 ('42153','Cobrador de donativos de obras de caridad'),
	 ('42161','Encuestadores');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('42162','Recopilador de datos'),
	 ('42210','Jefe de empleados de agencias de viajes'),
	 ('42211','Empleado de agencia de viajes'),
	 ('42212','Empleado de viajes de empresas de línea aérea o de línea marítima'),
	 ('42221','Informante al público'),
	 ('42222','Recepcionista'),
	 ('42231','Telefonista'),
	 ('42232','Operador de central telefónica'),
	 ('51111','Azafata de avión'),
	 ('51112','Azafata de información de aeropuerto');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51113','Comisario de avión'),
	 ('51114','Mayordomo de barco'),
	 ('51115','Camarero de barco'),
	 ('51121','Guarda de ómnibus'),
	 ('51122','Guarda de tren'),
	 ('51131','Guía de museos'),
	 ('51132','Guía de turismo'),
	 ('51133','Guía de viajes y excursiones'),
	 ('51134','Guía de expedición de caza'),
	 ('51135','Guía de parques naturales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51211','Ecónomo'),
	 ('51212','Mayordomo, gobernanta o ama de llaves'),
	 ('51213','Administrador de campamento de turismo'),
	 ('51214','Administrador de hogar estudiantil'),
	 ('51220','Jefe de cocina'),
	 ('51221','Cocinero'),
	 ('51222','Asador de parrilla'),
	 ('51223','Pastelero o repostero'),
	 ('51230','Jefe de mozos'),
	 ('51231','Mozo o camarero de bar o restorán');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51232','Barman'),
	 ('51233','Cantinero y tabernero'),
	 ('51311','Niñera o baby-sitter'),
	 ('51312','Auxiliar de guardería escolar'),
	 ('51313','Cuidadora de hogar infantil'),
	 ('51321','Ayudante de consultorio dental o asistente de consultorio dental'),
	 ('51322','Ayudante de enfermería'),
	 ('51323','Ayudante de ambulancia'),
	 ('51324','Camillero'),
	 ('51331','Ayudante de enfermería a domicilio');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51391','Ayudante de farmacia'),
	 ('51392','Ayudante de veterinaria'),
	 ('51399','Trabajadores de los cuidados personales y afines, n.c.b.o.e.'),
	 ('51411','Peluquero o barbero'),
	 ('51412','Peinadora y peluquera'),
	 ('51413','Esteticista'),
	 ('51414','Cosmetólogo'),
	 ('51415','Manicura'),
	 ('51416','Pedicuro'),
	 ('51417','Bañero en baños de sauna');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51418','Encargado de vestuario y pelucas en teatro'),
	 ('51419','Maquillador de cine o teatro'),
	 ('51421','Acompañante o Ama de compañía'),
	 ('51422','Acompañante de ómnibus escolar'),
	 ('51423','Cuidador de enfermos'),
	 ('51430','Jefe de empleados de pompas fúnebres'),
	 ('51431','Amortajador o embalsamador'),
	 ('51432','Empleado de pompas fúnebres'),
	 ('51491','Otros trabajadores de servicios personales a particulares, n.c.b.o.e.'),
	 ('51511','Astrólogo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51521','Adivinador'),
	 ('51522','Quiromántico'),
	 ('51523','Cartomántico'),
	 ('51610','Jefe de bomberos'),
	 ('51611','Bombero'),
	 ('51621','Oficial de policía'),
	 ('51622','Sub-oficial de policía'),
	 ('51623','Agente de policía'),
	 ('51624','Agente de policía de tránsito'),
	 ('51625','Agente de policía de carreteras');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('51626','Coracero o granadero'),
	 ('51629','Policía n.c.b.o.e.'),
	 ('51631','Carcelero o guardián de cárcel o prisión'),
	 ('51691','Salvavidas o bañero'),
	 ('51692','Guardaespaldas'),
	 ('51693','Guardián de costa o playa'),
	 ('51694','Guardián de reserva natural o guardabosque'),
	 ('51699','Personal de los servicios de protección y seguridad n.c.b.o.e.'),
	 ('52100','Jefe de modelos de moda, arte o publicidad'),
	 ('52101','Modelo de modas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('52102','Modelo de publicidad'),
	 ('52103','Modelo de fotografía'),
	 ('52210','Jefe de vendedores'),
	 ('52211','Vendedor en mostrador'),
	 ('52212','Vendedor en estación de gasolina'),
	 ('52219','Vendedor n.c.b.o.e.'),
	 ('52221','Promotor de ventas o demostrador'),
	 ('52222','Promotor-vendedor de servicios'),
	 ('52301','Vendedor de puesto callejero'),
	 ('52302','Vendedor de quiosco o Quiosquero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('52303','Vendedor de puesto de feria'),
	 ('61110','Capataz de trabajadores calificados de cultivos extensivos'),
	 ('61111','Agricultor o trabajador calificado de cultivo de algodón'),
	 ('61112','Agricultor o trabajador calificado de cultivo de arroz'),
	 ('61113','Agricultor o trabajador calificado de cultivo de caña de azúcar'),
	 ('61114','Agricultor o trabajador calificado de cultivo de cereales'),
	 ('61115','Agricultor o trabajador calificado de cultivo de hortalizas o de granja'),
	 ('61116','Agricultor o trabajador calificado de cultivo de tabaco'),
	 ('61117','Trabajador agrícola calificado en irrigación'),
	 ('61119','Trabajador agrícola calificado en cultivo extensivo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61120','Capataz de trabajadores calificados de plantaciones de árboles y arbustos'),
	 ('61121','Fruticultor o trabajador calificado de árboles frutales'),
	 ('61122','Arboricultor de arbustos'),
	 ('61123','Viticultor o trabajador agrícola calificado en viticultura'),
	 ('61130','Capataz de trabajadores calificados de huertas, invernaderos, viveros y jardines'),
	 ('61131','Horticultor, hortelano o trabajador calificado en horticultura'),
	 ('61132','Jardinero'),
	 ('61133','Trabajador agrícola calificado de vivero'),
	 ('61134','Cultivador de hongos o champiñones'),
	 ('61135','Floricultor');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61141','Agricultor o trabajador agrícola calificado en policultivos'),
	 ('61199','Agricultores y trabajadores calificados de cultivos para el mercado n.c.b.o.e.'),
	 ('61210','Capataz de trabajadores en cría de ganado o producción de leche y derivados'),
	 ('61211','Criador de ganado bovino, cabañero o trabajador calificado de ganado bovino'),
	 ('61212','Criador de ganado lechero, ordeñador u otros trabajadores calificados de la producción de leche'),
	 ('61213','Criador de ganado ovino, esquilador u otros trabajadores calificados de ganado lanar'),
	 ('61214','Criador de caballos'),
	 ('61215','Criador de ganado porcino o trabajador calificado de ganado porcino'),
	 ('61216','Cunicultor o trabajador calificado de cría de conejos'),
	 ('61217','Criador de perros, gatos y animales domésticos afines');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61218','Inseminador de ganado'),
	 ('61219','Ganadero o trabajador calificado de ganadería'),
	 ('61220','Capataz de trabajadores calificados de la avicultura'),
	 ('61221','Avicultor'),
	 ('61222','Trabajador calificado de la avicultura'),
	 ('61231','Apicultor'),
	 ('61232','Trabajador calificado en apicultura'),
	 ('61241','Criador de criadero diversificado'),
	 ('61242','Trabajador calificado de criadero diversificado'),
	 ('61291','Criador de aves y pájaros domésticos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61292','Cuidador de animales en parque zoológico o en reservas naturales'),
	 ('61293','Criador o trabajador de animales no domésticos para pieles finas'),
	 ('61294','Adiestrador de perros'),
	 ('61295','Criador de lombrices'),
	 ('61296','Domador de caballos'),
	 ('61297','Entrenador de caballos de carrera'),
	 ('61299','Criadores y trabajadores de la cría de animales n.c.b.o.e.'),
	 ('61300','Capataz de trabajadores agropecuarios calificados'),
	 ('61301','Productor agropecuario'),
	 ('61302','Trabajador agropecuario calificado');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61303','Chacarero, chacrero o quintero'),
	 ('61410','Supervisor forestal o capataz de trabajadores forestales calificados'),
	 ('61411','Escalador podador de árboles'),
	 ('61412','Podador'),
	 ('61413','Talador'),
	 ('61414','Trozador de árboles'),
	 ('61415','Aserrador de monte'),
	 ('61416','Hachero, monteador o leñador'),
	 ('61417','Plantador de árboles'),
	 ('61418','Descortezador de árboles');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61419','Trabajador forestal calificado'),
	 ('61421','Carbonero de carbón vegetal'),
	 ('61511','Piscicultor'),
	 ('61512','Marisquero'),
	 ('61513','Cultivador de algas'),
	 ('61519','Trabajador calificado de piscicultura'),
	 ('61520','Capataz de pescadores de agua dulce y en aguas costeras'),
	 ('61521','Buzo pescador'),
	 ('61522','Pescador de mejillones o mariscos'),
	 ('61523','Pescador de ríos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('61524','Pescador costero'),
	 ('61529','Trabajador calificado en pesca de agua dulce o aguas costeras'),
	 ('61530','Capataz de pescadores de alta mar'),
	 ('61531','Pescador de altura'),
	 ('61539','Trabajador calificado de pesca en alta mar'),
	 ('61541','Cazador'),
	 ('61542','Cazador de lobos de mar'),
	 ('61543','Cazador de nutrias'),
	 ('61544','Trampero de pieles'),
	 ('61599','Pescadores, cazadores, tramperos n.c.b.o.e.');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('62101','Agricultor de subsistencia'),
	 ('62102','Pescador de subsistencia'),
	 ('62109','Trabajador agropecuario de subsistencia'),
	 ('71110','Capataz de mineros y canteros'),
	 ('71111','Minero'),
	 ('71112','Cantero o granitero'),
	 ('71121','Dinamitero, pegador de minas o canteras'),
	 ('71130','Capataz de labrantes y labradores de piedra'),
	 ('71131','Cortador y amolador de piedra'),
	 ('71132','Aserrador y labrante de piedra');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71133','Tallador, grabador y pulidor de piedra'),
	 ('71134','Clasificador de piedras'),
	 ('71135','Mampostero o adornista de monumentos'),
	 ('71211','Constructor de casas o edificios con materiales tradicionales'),
	 ('71220','Capataz de albañilería'),
	 ('71221','Albañil de construcción'),
	 ('71222','Mampostero de construcción'),
	 ('71223','Albañil de material refractario'),
	 ('71224','Pavimentador'),
	 ('71230','Capataz de operarios de cemento armado');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71231','Encofrador de cemento'),
	 ('71232','Armador de hormigón armado'),
	 ('71233','Enfoscador de hormigón'),
	 ('71239','Cementista'),
	 ('71240','Capataz de carpintería gruesa'),
	 ('71241','Carpintero de construcción'),
	 ('71242','Carpintero de taller'),
	 ('71243','Carpintero de armado'),
	 ('71244','Carpintero de astillero naval'),
	 ('71245','Carpintero de puertas y ventanas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71246','Carpintero de decorados'),
	 ('71247','Carpintero de trabajos de mantenimiento'),
	 ('71249','Carpintero n.c.b.o.e.'),
	 ('71291','Montador de andamios'),
	 ('71292','Operario de construcción en trabajos a gran altura'),
	 ('71293','Demoledor de edificios u operario especializado en demolición'),
	 ('71294','Colocador de cables subterráneos'),
	 ('71295','Ensamblador o montador de elementos prefabricados'),
	 ('71296','Pocero'),
	 ('71297','Apuntalador de edificación');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71298','Operario de mantenimiento de edificios'),
	 ('71299','Oficiales y operarios de la construcción y afines n.c.b.o.e.'),
	 ('71311','Quinchador o techador con quincho'),
	 ('71312','Techador con tejas o entejador'),
	 ('71319','Techador n.c.b.o.e.'),
	 ('71321','Embaldosador o enlosador'),
	 ('71322','Parquetero, colocador o pulidor de pisos de madera'),
	 ('71323','Azulejista'),
	 ('71324','Marmolista'),
	 ('71331','Revocador');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71332','Estucador-decorador de yeso'),
	 ('71333','Yesero o enlucidor con yeso'),
	 ('71341','Instalador de aislación térmica'),
	 ('71342','Instalador de isonorización'),
	 ('71343','Instalador de refrigeración o climatización'),
	 ('71344','Operario de trabajos de aislación'),
	 ('71351','Vidriero-colocador'),
	 ('71352','Vidriero de automóviles'),
	 ('71353','Vidriero de vidrierías artísticas'),
	 ('71354','Operario de trabajos de vidriería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71359','Vidriero n.c.b.o.e.'),
	 ('71360','Capataz de sanitaria'),
	 ('71361','Instalador sanitario'),
	 ('71362','Instalador de tuberías de gas'),
	 ('71363','Instalador de tuberías de ventilación'),
	 ('71364','Colocador de tubos y conductos'),
	 ('71365','Excavador de pozos de agua'),
	 ('71366','Operario de sanitaria o plomero'),
	 ('71369','Sanitario o fontanero'),
	 ('71370','Capataz de electricidad');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74423','Aparador de calzado'),
	 ('71371','Instalador electricista o electricista de construcción'),
	 ('71372','Electricista de alumbrado'),
	 ('71373','Electricista de aeronaves o buques'),
	 ('71374','Electricista en vehículos de motor'),
	 ('71375','Electricista de mantenimiento de edificios'),
	 ('71376','Electricista de escenarios y teatros'),
	 ('71377','Luminotécnico en letreros luminosos'),
	 ('71379','Electricista n.c.b.o.e.'),
	 ('71410','Capataz de pintura');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('71411','Pintor de construcciones y edificios'),
	 ('71412','Pintor de casco de buques'),
	 ('71413','Empapelador'),
	 ('71414','Pintor-decorador de edificios'),
	 ('71415','Pintor de decorados de cine y teatro'),
	 ('71421','Pintor o barnizador de productos manufacturados'),
	 ('71422','Pintor de vehículos'),
	 ('71423','Pintor o barnizador de metales'),
	 ('71431','Limpiador de fachadas con chorros de arena o vapor'),
	 ('71432','Deshollinador');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72110','Capataz de moldeadores y macheros de fundición'),
	 ('72111','Moldeador de fundición'),
	 ('72112','Machero de fundición'),
	 ('72113','Matricero de fundición'),
	 ('72120','Capataz de soldadura'),
	 ('72121','Soldador con soplete a gas'),
	 ('72122','Soldador por arco eléctrico'),
	 ('72123','Soldador por resistencia eléctrica o puntos'),
	 ('72124','Cobresoldador'),
	 ('72125','Oxicortador');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72129','Soldador n.c.b.o.e.'),
	 ('72130','Capataz de chapistas'),
	 ('72131','Calderero de cobre y aleaciones ligeras'),
	 ('72132','Chapista de carrocerías'),
	 ('72133','Chapista de muebles de metal'),
	 ('72134','Chapista en decoración u ornamentación'),
	 ('72135','Hojalatero'),
	 ('72140','Capataz de montadores de estructuras metálicas'),
	 ('72141','Montador de estructuras y armazones metálicas'),
	 ('72142','Remachador');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72143','Armador de blindaje de buques'),
	 ('72144','Trazador de estructuras metálicas'),
	 ('72151','Aparejador'),
	 ('72152','Ajustador de cordajes'),
	 ('72153','Montador o empalmador de cables'),
	 ('72161','Buzo'),
	 ('72162','Hombre rana de salvamento'),
	 ('72163','Operario de trabajos subacuáticos'),
	 ('72210','Capataz de herrería'),
	 ('72211','Herrero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72212','Forjador'),
	 ('72213','Forjador de herramientas'),
	 ('72214','Fundidor de piezas de moldeo'),
	 ('72215','Trefilador de alambre'),
	 ('72216','Martillador'),
	 ('72221','Herramentista'),
	 ('72222','Matricero de herramientas'),
	 ('72223','Mecánico ajustador de herramientas y matrices'),
	 ('72224','Trazador de metales'),
	 ('72225','Ajustador herramentista de máquinas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72226','Ajustador de calibradores'),
	 ('72227','Armero'),
	 ('72228','Cerrajero'),
	 ('72230','Capataz de reguladores de máquinas herramientas'),
	 ('72231','Regulador-operador de taladradora de metales'),
	 ('72232','Regulador-tornero u operador de torno de metales'),
	 ('72233','Regulador-operador de cepilladora de metales'),
	 ('72234','Regulador-operador de fresadora de metales'),
	 ('72235','Regulador-operador de esmeriladora de metales'),
	 ('72236','Regulador-operador de mandriladora de metales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72237','Regulador-operador de rectificadora de metales'),
	 ('72238','Regulador-operador de extrusora de metales'),
	 ('72239','Regulador de máquinas herramientas n.c.b.o.e.'),
	 ('72241','Afilador de herramientas'),
	 ('72242','Afilador de cuchillería, sierras y otros instrumentos cortantes'),
	 ('72243','Amolador o reparador de sierras'),
	 ('72244','Bruñidor de metales'),
	 ('72245','Pulidor de metales'),
	 ('72246','Limpiador de metales'),
	 ('72247','Rectificador de metales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72299','Herreros, herramentistas y afines, n.c.b.o.e.'),
	 ('72310','Capataz de mecánica en vehículos de motor'),
	 ('72311','Mecánico de automóviles'),
	 ('72312','Mecánico de ferrocarriles'),
	 ('72313','Mecánico de camiones, autobuses o tractores'),
	 ('72314','Mecánico de motocicletas o bicicletas'),
	 ('72319','Mecánico de vehículos de motor n.c.b.o.e.'),
	 ('72320','Capataz de mecánica en motores de avión'),
	 ('72321','Mecánico de motores de avión'),
	 ('72322','Ajustador de motores de avión');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72330','Capataz de mecánica en maquinaria agrícola e industrial'),
	 ('72331','Mecánico de máquinas agrícolas'),
	 ('72332','Mecánico de máquinas de la construcción'),
	 ('72333','Mecánico de maquinaria industrial'),
	 ('72334','Mecánico de máquinas de la minería'),
	 ('72335','Mecánico de máquinas herramientas'),
	 ('72336','Mecánico de turbinas o de motores agrícolas e industriales diesel'),
	 ('72337','Mecánico naval'),
	 ('72338','Montador-instalador de maquinaria'),
	 ('72339','Mecánico ajustador o reparador de máquinas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72410','Capataz de mecánicos en electricidad'),
	 ('72411','Electricista de aparatos de señalización'),
	 ('72412','Electricista e instalador de ascensores'),
	 ('72413','Electricista de dínamos y motores o bobinador'),
	 ('72414','Electricista de refrigeración y climatización'),
	 ('72415','Reparador de aparatos eléctricos'),
	 ('72419','Mecánico-electricista n.c.b.o.e.'),
	 ('72420','Capataz de mecánicos de electrónica'),
	 ('72421','Ajustador electrónico de computadoras o mecánico de computadoras'),
	 ('72422','Ajustador electrónico de maquinaria industrial');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72423','Ajustador electrónico de aparatos de grabación y transmisión de sonido e imagen'),
	 ('72424','Ajustador electrónico de televisión, radio o radar'),
	 ('72429','Ajustador electrónico o mecánico-electrónico n.c.b.o.e.'),
	 ('72431','Mecánico de máquinas de contabilidad o de oficina'),
	 ('74121','Panadero o amasador de panadería'),
	 ('72432','Reparador de receptores de radio y televisión'),
	 ('72433','Mecánico-electrónico de aparatos de grabación y transmisión de sonido e imagen'),
	 ('72434','Instalador de antenas de radio o televisión o antenista'),
	 ('72439','Mecánico-reparador de equipos o aparatos electrónicos n.c.b.o.e.'),
	 ('72440','Capataz de mecánicos de instalaciones telefónicas o telegráficas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('72441','Mecánico de instalaciones telefónicas o telegráficas'),
	 ('72442','Reparador de instalaciones telefónicas o telegráficas'),
	 ('72443','Instalador de teléfonos'),
	 ('72450','Capataz de instaladores de líneas eléctricas'),
	 ('72451','Instalador de líneas de energía eléctrica'),
	 ('72452','Instalador de líneas de teléfonos'),
	 ('72453','Empalmador de cables eléctricos'),
	 ('72454','Empalmador de cables de teléfonos'),
	 ('72455','Instalador de cables subterráneos'),
	 ('73110','Capataz de mecánicos de instrumentos de precisión');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73111','Relojero'),
	 ('73112','Mecánico-reparador de cámaras fotográficas o instrumentos de óptica'),
	 ('73113','Mecánico de instrumentos de medicina u odontología'),
	 ('73114','Laboratorista dental y de prótesis dentales'),
	 ('73119','Mecánico o reparador de instrumentos científicos o de precisión n.c.b.o.e.'),
	 ('73121','Constructor de instrumentos musicales o luthier'),
	 ('73122','Reparador o afinador de instrumentos musicales'),
	 ('73131','Joyero'),
	 ('73132','Orfebre'),
	 ('73133','Tallador pulidor de joyería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73134','Grabador de platería y joyería'),
	 ('73210','Capataz de alfarería o cerámica'),
	 ('73211','Ceramista'),
	 ('73212','Modelista de cerámica y porcelana'),
	 ('73213','Moldeador de cerámica y porcelana'),
	 ('73214','Esmaltador de porcelana'),
	 ('73215','Tornero alfarero o de cerámica'),
	 ('73216','Prensador de cerámica'),
	 ('73217','Operador de máquina cortadora de ladrillos y tejas'),
	 ('73220','Capataz de operarios de cristalería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73221','Cortador de vidrio'),
	 ('73222','Modelador o moldeador de vidrio'),
	 ('73223','Laminador de vidrio'),
	 ('73224','Pulidor de vidrio'),
	 ('73225','Curvador de tubos de vidrio'),
	 ('73226','Biselador de cristales'),
	 ('73227','Cortador o modelador de cristales de óptica'),
	 ('73228','Pulidor o tallador de cristales de óptica'),
	 ('73231','Grabador de vidrio o de cristal'),
	 ('73232','Esmerilador de vidrio decorativo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73233','Tallador de cristales y vidrios'),
	 ('73241','Esmaltador o azogador'),
	 ('73242','Pintor-decorador de vidrio, cerámica y otros materiales'),
	 ('73243','Pintor de anuncios, carteles o letreros'),
	 ('73310','Capataz de artesanos de madera y materiales similares'),
	 ('73311','Artesano de artículos de la madera'),
	 ('73312','Artesano de artículos de piedra'),
	 ('73313','Artesano-tejedor de mimbre'),
	 ('73314','Grabador de hueso, marfil y plástico'),
	 ('73315','Artesano en papel o cartón');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73320','Capataz de artesanos del tejido, cuero y materiales similares'),
	 ('73321','Artesano de artículos de cuero'),
	 ('73322','Artesano de prendas de vestir tejidas'),
	 ('73323','Artesano-tejedor de alfombras'),
	 ('73399','Artesano n.c.b.o.e.'),
	 ('73410','Capataz de cajistas, tipógrafos y afines'),
	 ('73411','Linotipista'),
	 ('73412','Tipógrafo'),
	 ('73413','Armador de páginas'),
	 ('73414','Cajista');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73415','Compaginador de fotocomposición'),
	 ('73416','Fototipista'),
	 ('73417','Operador de teclado monotipista'),
	 ('73418','Preparador de planchas de imprenta Braille'),
	 ('73419','Impresor'),
	 ('73420','Capataz de estereotipistas y galvanotipistas'),
	 ('73421','Estereotipista'),
	 ('73422','Clisador de galvanotipia'),
	 ('73423','Matricero de imprenta'),
	 ('73424','Moldeador de clisés de imprenta');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73430','Capataz de grabadores de imprenta y fotograbadores'),
	 ('73431','Fotograbador'),
	 ('73432','Grabador de planchas o cilindros metálicos para imprenta'),
	 ('73433','Grabador de imprenta al aguafuerte'),
	 ('73434','Fotógrafo para imprenta'),
	 ('73435','Fotomecánico'),
	 ('73436','Huecograbador para imprenta'),
	 ('73437','Litógrafo o grabador de piedras litográficas para imprenta'),
	 ('73438','Tirador de pruebas de clisés para imprenta'),
	 ('73439','Transportador de fotograbado o litografía');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73441','Operario de laboratorio fotográfico'),
	 ('73442','Revelador de películas radiográficas'),
	 ('73443','Revelador de películas fotográficas'),
	 ('73451','Encuadernador'),
	 ('73452','Repujador de encuadernación'),
	 ('73453','Grabador o dorador de encuadernación'),
	 ('73454','Cosedor y encolador de encuadernación'),
	 ('73455','Guillotinero y recortador de encuadernación'),
	 ('73456','Compaginador de encuadernación'),
	 ('73461','Estampador o impresor en textiles');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('73462','Impresor a la plancha'),
	 ('73463','Impresor de serigrafía'),
	 ('74100','Capataz de frigorífico'),
	 ('74101','Matarife, degollador o desollador de reses'),
	 ('74102','Desplumador frigorífico'),
	 ('74103','Carneador, cortador o cuartero de carne'),
	 ('74104','Desgrasador o grasero de carne'),
	 ('74105','Deshuesador o desosador de carne'),
	 ('74106','Tripero'),
	 ('74107','Chacinero o fiambrero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74108','Ahumador, charqueador o salador de carne'),
	 ('74109','Carnicero'),
	 ('74110','Capataz de pescaderos'),
	 ('74111','Filetero manual'),
	 ('74112','Ahumador de pescados'),
	 ('74113','Salador de pescado'),
	 ('74114','Pelador de camarones'),
	 ('74119','Pescadero'),
	 ('74120','Maestro de pala'),
	 ('74122','Pastelero o facturero de panadería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74123','Confitero o dulcero'),
	 ('74124','Operario de fabricación de galletas'),
	 ('74125','Operario de fabricación de pastas alimenticias, fideero o pastero'),
	 ('74126','Operario de fabricación de chicle'),
	 ('74127','Operario de fabricación de chocolates'),
	 ('74128','Pizzero'),
	 ('74129','Repostero de panadería'),
	 ('74130','Capataz de operarios de elaboración de productos lácteos'),
	 ('74131','Quesero o fundidor de quesos'),
	 ('74132','Heladero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74133','Mantequero'),
	 ('74140','Capataz de operarios de conservación de frutas, legumbres, verduras y afines'),
	 ('74141','Conservero u operario de conservación de frutas'),
	 ('74142','Conservero u operario de conservación de legumbres y verduras'),
	 ('74151','Catador de vinos'),
	 ('74152','Catador de licores'),
	 ('74153','Clasificador de alimentos'),
	 ('74160','Capataz de trabajadores tabacaleros'),
	 ('74161','Preparador y elaborador de tabaco y sus productos'),
	 ('74199','Oficiales y operarios del procesamiento de alimentos, n.c.b.o.e.');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74210','Capataz de operarios del tratamiento de la madera'),
	 ('74211','Operario de tratamiento de madera'),
	 ('74220','Capataz de ebanistas y afines'),
	 ('74221','Ebanista'),
	 ('74222','Enchapador, lustrador o barnizador de muebles de madera'),
	 ('74223','Confeccionador de marcos para cuadros'),
	 ('74224','Tonelero o constructor de toneles y barriles'),
	 ('74225','Modelista en madera'),
	 ('74226','Maquetista de madera'),
	 ('74227','Confeccionador de artículos de madera para deportes');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74228','Tallador en madera'),
	 ('74229','Mueblero o restaurador de muebles'),
	 ('74230','Capataz de aserradero'),
	 ('74231','Regulador-aserrador u operador de sierra'),
	 ('74232','Regulador-ensamblador u operador de ensambladora de madera'),
	 ('74233','Regulador-operador de lijado o de cepilladora de la madera'),
	 ('74234','Regulador-operador de fresadora o de grabadora de la madera'),
	 ('74235','Regulador-operador de molduradora o de ranuradora de madera'),
	 ('74236','Regulador-operador de torno de madera'),
	 ('74239','Operador o regulador de máquinas de labrar madera no clasificabo bajo otros epígrafes');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74241','Cestero o canastero'),
	 ('74242','Confeccionador de muebles de mimbre o caña o mimbrero'),
	 ('74243','Escobero'),
	 ('74244','Trenzador de cestos u objetos de paja'),
	 ('74245','Confeccionador de cepillos y brochas, cepillero o pincelero'),
	 ('74246','Plumerero'),
	 ('74310','Capataz de preparadores de fibras textiles'),
	 ('74311','Torcedor o estirador de fibras textiles'),
	 ('74312','Peinador de fibras textiles'),
	 ('74313','Cardador de fibras textiles');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74314','Clasificador de lana o clasificador de fibras textiles'),
	 ('74315','Lavador de lana'),
	 ('74316','Mezclador de fibras textiles'),
	 ('74319','Preparador de fibras textiles'),
	 ('74320','Capataz de hilandería o tejeduría'),
	 ('74321','Hilandero'),
	 ('74322','Tejedor de punto'),
	 ('74323','Tejedor de telar'),
	 ('74324','Tejedor de redes de pesca'),
	 ('74325','Zurcidor o remendador de tejidos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74326','Tejedor de tapicería y alfombras'),
	 ('74331','Modisto'),
	 ('74332','Sastre'),
	 ('74333','Sombrerero'),
	 ('74334','Modisto de cine, teatro o televisión'),
	 ('74335','Camisero'),
	 ('74336','Pantalonero'),
	 ('74337','Confeccionador de lencería'),
	 ('74340','Capataz de peleteros'),
	 ('74341','Peletero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74342','Escogedor y combinador de pieles'),
	 ('74343','Cortador de pieles'),
	 ('74350','Capataz de patronistas y cortadores de cuero, tela y afines'),
	 ('74351','Patronista de prendas de vestir'),
	 ('74352','Patronista de pieles'),
	 ('74353','Cortador de prendas de vestir'),
	 ('74354','Cortador de prendas de cuero y piel'),
	 ('74355','Patronista y cortador de tapicería'),
	 ('74356','Patronista y cortador de guantes'),
	 ('74357','Patronista de lencería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74358','Copista de dibujos'),
	 ('74360','Capataz de cosedores y bordadores y afines'),
	 ('74361','Cosedor de prendas de vestir, de cuero o de piel'),
	 ('74362','Cosedor de telas de tapicería, de velas, tiendas, carpas, colchas o colchones'),
	 ('74363','Bordador a mano'),
	 ('74364','Confeccionador de juguetes y muñecos blandos'),
	 ('74365','Confeccionador de flores artificiales'),
	 ('74369','Costurero n.c.b.o.e.'),
	 ('74371','Tapicero de muebles'),
	 ('74372','Tapicero de vehículos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74373','Colchonero'),
	 ('74374','Confeccionador de colchas y edredones'),
	 ('74399','Oficiales y operarios de los textiles y de la confección y afines, n.c.b.o.e.'),
	 ('74400','Capataz de apelambradores, pellejeros y curtidores'),
	 ('74401','Clasificador de cueros, pieles y pellejos'),
	 ('74402','Curtidor'),
	 ('74403','Depilador o rasurador de pieles'),
	 ('74404','Descarnador de cueros'),
	 ('74405','Estirador de cueros y pieles'),
	 ('74406','Pelador de cueros y pellejos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74407','Teñidor de cueros o pieles'),
	 ('74408','Tintorero de cueros o pieles'),
	 ('74409','Lustrador de pieles'),
	 ('74411','Lavador de cueros'),
	 ('74412','Cortador de cuero'),
	 ('74413','Cosedor de cuero'),
	 ('74414','Repujador de cuero'),
	 ('74415','Troquelador de cuero'),
	 ('74416','Salador de cueros'),
	 ('74417','Lustrador de cueros');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74418','Confeccionador de sillas de montar y arneses'),
	 ('74419','Talabartero'),
	 ('74420','Capataz de fábrica de calzado'),
	 ('74421','Acabador de calzado'),
	 ('74422','Armador u hormero de calzado'),
	 ('74424','Preparador, cortador, raspador, pegador y montador de palas de calzado'),
	 ('74425','Preparador, separador y montador de suelas de calzado'),
	 ('74426','Patronista de calzado'),
	 ('74427','Teñidor de calzado'),
	 ('74428','Alpargatero o aparador de calzado de tela');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('74429','Zapatero reparador'),
	 ('74499','Oficiales y operarios de las pieles, cuero y calzado, n.c.b.o.e.'),
	 ('81110','Capataz de operadores de instalaciones mineras'),
	 ('81111','Operador de máquina perforadora de minas y canteras'),
	 ('81120','Capataz operadores de instalaciones de procesamiento de minerales y rocas'),
	 ('81121','Operador de máquina labradora de piedra'),
	 ('81122','Operador de máquina quebrantadora o de máquina pulverizadora de piedra'),
	 ('81123','Operador de máquina aserradora de piedra o cortador de piedra'),
	 ('81129','Operador de máquina de procesamiento de piedra n.c.b.o.e.'),
	 ('81131','Sondista perforador de pozos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81210','Capataz de operadores de hornos de primera fusión de metales'),
	 ('81211','Operador de hornos de minerales y de hornos de primera fusión de metales'),
	 ('81220','Capataz de operadores de hornos de segunda fusión de metales'),
	 ('81221','Operador de laminadora de metales'),
	 ('81222','Operador de máquina moldeadora de metales'),
	 ('81223','Operador de horno de segunda fusión'),
	 ('81230','Capataz de operadores de instalaciones de tratamiento térmico de metales'),
	 ('81231','Operador de instalaciones de tratamiento térmico de metales'),
	 ('81240','Capataz de operadores de máquinas trefiladoras y estiradoras de metales'),
	 ('81241','Operador de máquina extrusora de metales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81242','Operador de máquina estiradora de metales'),
	 ('81243','Operador de máquina trefiladora de alambre'),
	 ('81310','Capataz de operadores de hornos de vidriería y máquinas afines'),
	 ('81311','Operador de horno de fabricación, fundición o recocido de vidrio'),
	 ('81312','Operador de máquina para el tratamiento del vidrio'),
	 ('81313','Operador de máquina para la terminación del vidrio'),
	 ('81314','Operador de máquina de fabricación de botellas u otros artículos de vidrio'),
	 ('81319','Operador de máquina para la elaboración o terminación del vidrio, n.c.b.o.e.'),
	 ('81320','Capataz de operadores de hornos de cerámica y máquinas afines'),
	 ('81321','Operador de horno de baldosas y briquetas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81322','Operador de horno de ladrillos y tejas o ladrillero'),
	 ('81323','Operador de horno de cerámica, loza y porcelana'),
	 ('81324','Operador de máquina de fabricación de loza y porcelana'),
	 ('81325','Operador de máquina de fabricación o tratamiento de cerámica'),
	 ('81391','Operador de máquina mezcladora de materiales de vidrio'),
	 ('81392','Operador de máquina de producción de fibra de vidrio'),
	 ('81393','Operador de máquina de preparación de esmaltes'),
	 ('81394','Operador de máquina trituradora de arcilla'),
	 ('81399','Operadores de instalaciones de vidriería, cerámica y afines, n.c.b.o.e.'),
	 ('81410','Capataz de operadores de procesamiento de la madera y afines');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81411','Aserrador u operador de instalaciones de aserradero'),
	 ('81412','Operador de sierra de cinta o de máquina cortadora de madera'),
	 ('81413','Operador de máquina cepilladora de madera'),
	 ('81414','Operador de máquina fresadora o de máquina perforadora de madera'),
	 ('81419','Operador de máquinas de procesamiento de la madera n.c.b.o.e.'),
	 ('81420','Capataz de operadores para la preparación de pasta para papel'),
	 ('81421','Operador de máquina de preparación de pasta para papel'),
	 ('81422','Operador de máquina trituradora, desfibradora o tamizadora para pasta para papel'),
	 ('81423','Operador de máquina batidora o refinadora de pasta para papel'),
	 ('81429','Operador de instalaciones de preparación o elaboración de pasta para papel, n.c.b.o.e.');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81430','Capataz de operadores de instalaciones para la fabricación de papel'),
	 ('81431','Operador de máquina aprestadora de papel'),
	 ('81432','Operador de máquina de fabricación de papel o cartón'),
	 ('81433','Operador de máquina de tratamiento de papel'),
	 ('81434','Cortador o guillotinero de papel'),
	 ('81435','Prensador de papel'),
	 ('81436','Bobinador de papel'),
	 ('81439','Operador de instalaciones de fabricación de papel o cartón n.c.b.o.e.'),
	 ('81510','Capataz de operadores de instalaciones quebrantadoras, trituradoras y mezcladoras de sustancias químicas'),
	 ('81511','Operador de instalaciones quebrantadoras, trituradoras o mezcladoras de sustancias químicas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81520','Capataz de operadores de instalaciones de tratamiento químico térmico'),
	 ('81521','Operador de máquina para tratamientos químicos térmicos'),
	 ('81522','Operador de instalaciones para la producción de cemento'),
	 ('81530','Capataz de operadores de equipos de filtración y separación de sustancias químicas'),
	 ('81531','Operador de instalaciones de tratamiento del petróleo crudo'),
	 ('81532','Operador de máquina separadora centrifugadora para tratamientos químicos'),
	 ('81533','Operador de aparatos de filtración para substancias químicas o filtrador de industria química'),
	 ('81540','Capataz de operadores de equipos de destilación y de reacción química'),
	 ('81541','Operador de alambique'),
	 ('81542','Destilador de productos químicos excepto petróleo');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81543','Operador de aparato de reacción conversión en procesos químicos (excepto petróleo y gas natural)'),
	 ('81544','Operador de máquina evaporadora de procesos químicos (excepto petróleo y gas natural)'),
	 ('81550','Capataz de operadores de instalaciones de refinación de petróleo y gas natural'),
	 ('81551','Operador de destilería de refinación de petróleo y gas natural'),
	 ('81559','Operador de instalaciones de refinación de petróleo y gas natural n.c.b.o.e.'),
	 ('81591','Operador de instalaciones de abonos artificiales'),
	 ('81592','Operador de instalaciones de producción de fibras sintéticas'),
	 ('81593','Operador de instalaciones para tratamiento de látex de caucho'),
	 ('81594','Operador de máquina de liquefacción de gases'),
	 ('81599','Operadores de instalaciones de tratamientos químicos n.c.b.o.e.');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81610','Capataz de operadores de instalaciones de producción de energía'),
	 ('81611','Operador de instalaciones de central hidroeléctrica o termoeléctrica'),
	 ('81612','Operador de cuadro de control de generadores'),
	 ('81613','Operador de cuadro de distribución de central eléctrica'),
	 ('81614','Operador-rectificador de energía eléctrica'),
	 ('81615','Repartidor de cargas de energía eléctrica'),
	 ('81621','Foguista de caldera'),
	 ('81622','Foguista de buque'),
	 ('81630','Capataz de operadores de instalaciones de tratamiento de agua y afines'),
	 ('81631','Operador de instalaciones de depuración y filtración de agua');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81632','Operador de instalaciones de estación de abastecimiento y bombeo de agua'),
	 ('81633','Operador de instalaciones de tratamiento de aguas servidas'),
	 ('81634','Operador de válvulas de desagüe de embalses'),
	 ('81635','Operador de instalaciones de incineración de residuos'),
	 ('81636','Operador de instalaciones de calefacción'),
	 ('81637','Operador de instalaciones de refrigeración'),
	 ('81638','Operador de compresor de gas o aire'),
	 ('81639','Operador de instalaciones de ventilación'),
	 ('81641','Operador de máquina de producción de hielo'),
	 ('81710','Capataz de operadores de cadenas de montaje automatizadas');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('81711','Operador de cadenas de montaje automatizadas'),
	 ('81720','Capataz de operadores de robots industriales'),
	 ('81721','Operador de robots industriales'),
	 ('82110','Capataz de operadores de máquinas herramientas'),
	 ('82111','Tornero de metalurgia'),
	 ('82112','Operador de máquina taladradora o ranuradora de metales'),
	 ('82113','Operador de máquina mandriladora de metales'),
	 ('82114','Operador de máquina de curvado de metales'),
	 ('82115','Operador de máquina fresadora de metales'),
	 ('82116','Operador de máquina para grabado de metales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82117','Operador de máquina oxicortadora de metales'),
	 ('82118','Operador de máquina rectificadora de metales'),
	 ('82119','Operador de máquina de forja de metales'),
	 ('82121','Operador de máquina lapidadora de metales'),
	 ('82122','Operador de cizalla mecánica'),
	 ('82123','Operador de máquina remachadora de metales'),
	 ('82124','Operador de cepilladora de metales'),
	 ('82125','Operador de esmeriladora de metales'),
	 ('82126','Operador de prensa mecánica para metales'),
	 ('82127','Operador de sierra mecánica para metales');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82128','Operador de máquina de estampado de metales'),
	 ('82129','Operador de máquinas herramientas n.c.b.o.e.'),
	 ('82130','Capataz de operadores de máquinas de fabricación de artículos mtetálicos'),
	 ('82131','Operador de máquina de fabricación de cables'),
	 ('82132','Operador de máquina de fabricación de conmutadores'),
	 ('82133','Operador de máquina de fabricación de joyas'),
	 ('82134','Operador de máquina de fabricación de tornillos, tuercas o alambre'),
	 ('82135','Operador de máquina de fabricación de tubos metálicos'),
	 ('82140','Capataz de operadores de máquinas para fabricar cemento y otros productos minerales'),
	 ('82141','Operador de máquina de grabado sobre productos de piedra');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82142','Operador de máquina pulidora de piedra'),
	 ('82143','Operador de instalaciones mezcladoras de hormigón'),
	 ('82144','Operador de máquina cortadora de productos de piedra o mosaicos'),
	 ('82145','Operador de máquina de fabricación de aglomerados de piedra artificial'),
	 ('82146','Operador de máquina de productos prefabricados de hormigón'),
	 ('82149','Operador de máquina de productos minerales n.c.b.o.e.'),
	 ('82210','Capataz de operadores de máquinas para fabricar productos farmacéuticos y cosméticos'),
	 ('82211','Operador de máquina de fabricación de detergentes'),
	 ('82212','Operador de máquina de fabricación de cosméticos'),
	 ('82213','Operador de máquina de fabricación de productos farmacéuticos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82221','Operador de máquina de fabricación de municiones'),
	 ('82222','Operador de máquina de fabricación de fósforos'),
	 ('82223','Operador de máquina de fabricación de productos de pirotecnia'),
	 ('82230','Capataz de operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales'),
	 ('82231','Galvanizador u operador de máquina de galvanoplastia'),
	 ('82232','Operador de máquina pulidora de metales'),
	 ('82233','Niquelador'),
	 ('82234','Anodizador'),
	 ('82235','Cromador'),
	 ('82236','Plateador');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82237','Operador de máquina bruñidora de metales'),
	 ('82238','Operador de máquina de pintura sobre metales'),
	 ('82239','Operador de máquina recubridora de metales'),
	 ('82241','Operador de máquina de revelado o ampliación de películas fotográficas'),
	 ('82242','Operador de máquina de revelado de películas cinematográficas'),
	 ('82291','Operador de máquina de producción de gas'),
	 ('82299','Operadores de máquinas para fabricar productos químicos n.c.b.o.e.'),
	 ('82310','Capataz de operadores de máquinas para fabricar productos de caucho'),
	 ('82311','Operador de máquina de tratamiento del caucho'),
	 ('82312','Operador de máquina de fabricación de neumáticos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82313','Operador de máquina recauchutadora de neumáticos'),
	 ('82314','Vulcanizador de caucho u operador de máquina vulcanizadora de artículos de caucho'),
	 ('82319','Operador de máquina de fabricación de productos de caucho n.c.b.o.e.'),
	 ('82320','Capataz de operadores de máquinas para fabricar productos de material plástico'),
	 ('82321','Operador de máquina amoladora de material plástico'),
	 ('82322','Operador de máquina cortadora de productos de material plástico'),
	 ('82323','Operador de máquina extrusora de material plástico'),
	 ('82324','Operador de máquina estiradora de material plástico'),
	 ('82325','Operador de máquina laminadora de material plástico'),
	 ('82326','Operador de máquina moldeadora de material plástico');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82327','Operador de máquina pulidora de material plástico'),
	 ('82328','Operador de máquina de grabado sobre material plástico'),
	 ('82329','Operador de máquina de fabricación de prductos de material plástico'),
	 ('82400','Capataz de operadores de máquinas para fabricar productos de madera'),
	 ('82401','Operador de máquina de labrado de madera'),
	 ('82402','Operador de máquina de tallado de madera'),
	 ('82403','Operador de máquina de grabado de madera'),
	 ('82404','Operador de máquina curvadora de madera'),
	 ('82405','Operador de máquina de acabado de madera'),
	 ('82406','Operador de máquina de pintura sobre madera');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82407','Operador de torno para trabajo de la madera'),
	 ('82408','Operador de máquina de fabricación de muebles'),
	 ('82409','Operador de máquina de fabricación de objetos de madera'),
	 ('82510','Capataz de operadores de máquinas de imprenta'),
	 ('82511','Operador de prensa por rotativa'),
	 ('82512','Operador de máquina de imprenta (fototipia u offset)'),
	 ('82513','Operador de máquina de impresión sobre textiles'),
	 ('82519','Operador de máquina de imprenta no clasificado bajo otros epígrafes'),
	 ('82521','Operador de máquina encuadernadora'),
	 ('82530','Capataz de operadores de máquinas para fabricar productos de papel');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82531','Operador de máquina de fabricación de artículos de papel'),
	 ('82532','Operador de máquina de fabricación de artículos de cartón'),
	 ('82610','Capataz de operadores de máquinas de preparación de fibras, hilado y devanado'),
	 ('82611','Operador de máquina bobinadora de hilo'),
	 ('82612','Operador de máquina devanadora'),
	 ('82613','Operador de máquina de hilado de hilo'),
	 ('82614','Operador de máquina de hilado de fibras sintéticas'),
	 ('82615','Operador de máquina lavadora de fibras textiles'),
	 ('82616','Operadora de máquina mezcladora de fibras textiles'),
	 ('82617','Operador de máquina peinadora de fibras textiles');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82618','Operador de máquina retorcedora de hilo'),
	 ('82619','Operador de máquina mechera de fibras textiles'),
	 ('82620','Capataz de operadores de máquinas tejedoras'),
	 ('82621','Operador de máquina tejedora'),
	 ('82622','Operador de máquina de fabricación de alfombras'),
	 ('82623','Operador de máquina de urdido'),
	 ('82624','Operador de máquina tejedora de calcetería'),
	 ('82625','Operador de máquina tejedora de encajes'),
	 ('82626','Operador de máquina de fabricación de mallas o redes'),
	 ('82629','Operador de telar');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82630','Capataz de operadores de máquinas para coser'),
	 ('82631','Operador de máquina de coser prendas de vestir y otros artículos textiles'),
	 ('82632','Operador de máquina de coser cuero'),
	 ('82633','Operador de máquina de coser pieles'),
	 ('82634','Operador de máquina de coser sombreros'),
	 ('82635','Operador de máquina de coser tapicería de muebles'),
	 ('82636','Operador de máquina de bordar'),
	 ('82637','Ribeteador textil'),
	 ('82639','Operador de máquinas de coser n.c.b.o.e.'),
	 ('82640','Capataz de operadores de máquinas de blanqueo, teñido y tintura');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82641','Operador de máquina blanqueadora de productos textiles o blanqueador de textiles'),
	 ('82642','Operador de máquina impermeabilizadora de productos textiles o impermeabilizador textil'),
	 ('82643','Operador de máquina lavadora de productos textiles o limpiador de tintorería'),
	 ('82644','Operador de máquina de planchado'),
	 ('82645','Operador de máquina de limpieza en seco'),
	 ('82646','Operador de máquina de secado de productos textiles'),
	 ('82647','Operador de máquina de tintura de hilados o prendas de vestir'),
	 ('82648','Operador de equipo de limpieza de alfombras y moquetes'),
	 ('82649','Calandrador textil'),
	 ('82650','Capataz de operadores de máquinas de tratamiento de pieles y cueros');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82651','Operador de máquina cortadora de cueros'),
	 ('82652','Operador de máquina depiladora de cueros'),
	 ('82653','Operador de máquina de descarne de cueros'),
	 ('82654','Operador de máquina de estirado de pieles'),
	 ('82655','Operador de máquina lavadora de cueros'),
	 ('82656','Operador de máquina de tintura de cueros'),
	 ('82659','Operador de máquina de curtiduría n.c.b.o.e.'),
	 ('82660','Capataz de operadores de máquinas para la fabricación de calzado o de marroquinería'),
	 ('82661','Operador de máquina para la fabricación de calzado'),
	 ('82662','Operador de máquina para la fabricación de artículos de marroquinería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82691','Operador de máquina de sombrerería'),
	 ('82692','Operador de máquina de fabricación de patrones textiles o de cuero'),
	 ('82693','Operador de máquina de fabricación de colchones'),
	 ('82699','Operadores de máquina para fabricar productos textiles y artículos de piel y cuero n.c.b.o.e.'),
	 ('82710','Capataz de operadores de máquinas para elaborar carne, pescado y mariscos'),
	 ('82711','Operador de máquina preparadora de carne o pescado'),
	 ('82712','Operador de máquina procesadora de carne o pescado'),
	 ('82713','Operador de máquina conservadora de carne o pescado'),
	 ('82714','Operador de máquina enlatadora de carne o pescado'),
	 ('82715','Operador de máquina congeladora de carne o pescado');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82716','Operador de máquina esterilizadora de carne pescado'),
	 ('82719','Operador de máquina de fabricación de productos de carne o pescado n.c.b.o.e.'),
	 ('82720','Capataz de operadores de máquinas para elaborar productos lácteos'),
	 ('82721','Operador de máquina pasteurizadora de leche'),
	 ('82722','Operador de máquina de elaboración de leche en polvo'),
	 ('82723','Operador de máquina refrigeradora de productos lácteos'),
	 ('82724','Salador de queso'),
	 ('82729','Operador de máquina de elaboración de productos lácteos, n.c.b.o.e.'),
	 ('82730','Capataz de operadores de máquinas de molienda de cereales o especias'),
	 ('82731','Operador de máquina descortezadora de granos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82732','Operador de molino de arroz'),
	 ('82733','Operador de molino de cereales'),
	 ('82734','Operador de molino de especias'),
	 ('82735','Operador de máquina de procesamiento de granos'),
	 ('82739','Molinero de cereales y especias'),
	 ('82740','Capataz de operadores de máquinas para elaborar cereales, productos de panadería y repostería y artículos de chocolate'),
	 ('82741','Operador de máquina de elaboración de pastas alimenticias'),
	 ('82742','Operador de máquina de elaboración de chocolates'),
	 ('82743','Operador de máquina de elaboración de pasteles'),
	 ('82744','Operador de máquina de panadería');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82745','Operador de máquina de elaboración de dulces'),
	 ('82746','Operador de máquina de repostería'),
	 ('82750','Capataz de operadores de máquinas para elaborar frutos húmedos y secos y hortalizas'),
	 ('82751','Operador de máquina de extracción o refinación de aceites comestibles'),
	 ('82752','Operador de máquina lavadora de frutas, legumbres o verduras'),
	 ('82753','Operador de máquina esterilizadora de frutas, legumbres o verduras'),
	 ('82754','Operador de máquina conservadora de fruta, legumbres o verduras'),
	 ('82755','Operador de máquina procesadora de fruta, legumbres o verduras'),
	 ('82756','Operador de máquina congeladora de fruta, legumbres o verduras'),
	 ('82757','Operador de máquina enlatadora de frutas, legumbres o verduras');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82758','Operador de máquina deshidratadora de alimentos'),
	 ('82759','Operador de máquina de producción de jugos de frutas o vegetales'),
	 ('82760','Capataz de operadores de máquinas para fabricar azúcares'),
	 ('82761','Operador de máquina de producción de azúcar'),
	 ('82762','Operador de máquina pulverizadora de azúcar'),
	 ('82763','Operador de difusoras de azúcar de remolacha'),
	 ('82764','Refinador de ingenio azucarero'),
	 ('82770','Capataz de operadores de máquinas para elaborar té, café y cacao'),
	 ('82771','Operador de máquina moledora de café'),
	 ('82772','Operador de máquina tostadora de café');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82773','Operador de máquina mezcladora de café'),
	 ('82774','Operador de máquina mezcladora de té'),
	 ('82775','Operador de máquina tostadora de cacao'),
	 ('82780','Capataz de operadores de máquinas para elaborar cerveza, vino y otras bebidas'),
	 ('82781','Operador de máquina de elaboración de bebidas sin alcohol'),
	 ('82782','Operador de máquina lavadora de botellas'),
	 ('82783','Operador de instalaciones de elaboración de vino'),
	 ('82784','Operador de máquina de elaboración de vinagre'),
	 ('82785','Operador de máquina de germinación o secado de malta'),
	 ('82786','Operador de máquina de fermentación o cocción de malta');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82787','Operador de máquina de producción de licores'),
	 ('82790','Capataz de operadores de máquinas para elaborar productos del tabaco'),
	 ('82791','Operador de máquina de productos de tabaco o tabacalero'),
	 ('82810','Capataz de montadores de mecanismos y elementos mecánicos'),
	 ('82811','Montador de maquinaria agrícola'),
	 ('82812','Montador de maquinaria industrial'),
	 ('82813','Montador de maquinaria mecánica'),
	 ('82814','Montador de mecanismos mecánicos'),
	 ('82815','Montador de motores de combustión'),
	 ('82816','Montador de vehículos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82817','Montador de maquinaria textil'),
	 ('82818','Montador de maquinaria de imprenta'),
	 ('82819','Montador de máquinas herramientas'),
	 ('82820','Capataz de montadores de equipos eléctricos'),
	 ('82821','Montador de componentes eléctricos o armador de artefactos eléctricos'),
	 ('82822','Operador de máquina bobinadora'),
	 ('82830','Capataz de montadores de equipos electrónicos'),
	 ('82831','Montador de componentes electrónicos'),
	 ('82832','Montador de equipos microelectrónicos'),
	 ('82833','Montador de receptores de radio');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82834','Montador de receptores de televisión'),
	 ('82835','Montador de tubos electrónicos'),
	 ('82836','Montador de instrumentos de precisión'),
	 ('82837','Montador de prótesis auditivas'),
	 ('82840','Capataz de montadores de productos metálicos, de caucho o de plástico'),
	 ('82841','Montador de muebles metálicos'),
	 ('82842','Montador de productos de metal'),
	 ('82843','Montador de productos de caucho'),
	 ('82844','Montador de productos de material plástico'),
	 ('82850','Capataz de montadores de productos de madera');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82851','Montador de muebles de madera'),
	 ('82859','Montador de productos de madera'),
	 ('82860','Capataz de montadores de productos de cartón, textiles y materiales afines'),
	 ('82861','Montador de productos de cartón'),
	 ('82862','Montador de productos de cuero'),
	 ('82863','Montador de productos textiles'),
	 ('82901','Operador de máquina capsuladora'),
	 ('82902','Operador de máquina embaladora'),
	 ('82903','Operador de máquina embotelladora'),
	 ('82904','Operador de máquina empalmadora de cabos y cables');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('82905','Operador de máquina enfardadora'),
	 ('82906','Operador de máquina etiquetadora, rotuladora o marcadora de mercadería'),
	 ('82907','Operador de máquina aglomeradora de piedra pulverizada'),
	 ('82908','Operador de máquina selladora'),
	 ('82909','Operador de calesita y otros tiovivos'),
	 ('83111','Conductor o maquinista de tren'),
	 ('83112','Ayudante de maquinista de tren'),
	 ('83120','Jefe de tren de mercancías'),
	 ('83121','Agente de maniobras de ferrocarril'),
	 ('83122','Operador de tráfico de trenes o derivador de ferrocarriles');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('83123','Operador de enganche de vagones de tren'),
	 ('83124','Guardafrenos de ferrocarril'),
	 ('83125','Guardagujas de ferrocarril'),
	 ('83211','Motociclista-mensajero'),
	 ('83212','Motociclista-repartidor'),
	 ('83221','Taxista o conductor de taxi'),
	 ('83222','Remisero o conductor de remise'),
	 ('83223','Conductor de camioneta o furgoneta'),
	 ('83224','Conductor de ambulancia'),
	 ('83225','Chofer de automóvil');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('83231','Conductor de autobús'),
	 ('83232','Conductor de microbús'),
	 ('83233','Conductor de ómnibus escolar'),
	 ('83241','Conductor de camión'),
	 ('83242','Conductor de camión con remolque'),
	 ('83243','Conductor con camión cisterna'),
	 ('83244','Conductor de camión volquete'),
	 ('83245','Fletero en camión'),
	 ('83249','Conductor de camiones pesados n.c.b.o.e.'),
	 ('83299','Conductores de vehículos de motor, n.c.b.o.e.');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('83310','Capataz de operadores de maquinaria agrícola y forestal motorizada'),
	 ('83311','Tractorista o conductor de tractor agrícola'),
	 ('83312','Operador de cosechadora'),
	 ('83313','Operador segadora o trilladora'),
	 ('83314','Conductor de máquina forestal para acarreo de rollizos'),
	 ('83319','Operador de maquinaria agrícola motorizada n.c.b.o.e.'),
	 ('83320','Capataz de operadores de máquinas de movimiento de tierras y afines'),
	 ('83321','Operador de excavadora'),
	 ('83322','Operador de pala mecánica'),
	 ('83323','Conductor de niveladora o bulldozer');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('83324','Operador de máquina aplanadora o apisonadora'),
	 ('83325','Conductor de draga'),
	 ('83326','Operador de máquina pavimentadora de hormigón'),
	 ('83327','Operador de máquina pavimentadora de alquitrán o alquitranador'),
	 ('83328','Operador de esparcidora de hormigón, alquitrán o piedras'),
	 ('83329','Operador de martillo neumático'),
	 ('83330','Capataz de operadores de grúas y aparatos elevadores'),
	 ('83331','Operador de grúa fija'),
	 ('83332','Operador de grúa flotante'),
	 ('83333','Operador de grúa móvil');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('83334','Operador de cinta o cable transportador'),
	 ('83335','Operador de puente giratorio'),
	 ('83336','Operador de dique seco'),
	 ('83337','Operador de montacargas'),
	 ('83341','Operador de horquilla elevadora'),
	 ('83399','Operadores de maquinaria agrícola móvil y de otras máquinas móviles, n.c.b.o.e.'),
	 ('83401','Contramaestre de barco'),
	 ('83402','Marinero'),
	 ('83403','Grumete'),
	 ('83404','Lanchero o conductor de lancha a motor');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('83405','Timonel'),
	 ('83406','Dragador'),
	 ('83407','Torrero o guardián de faro'),
	 ('91111','Feriante de alimentos'),
	 ('91112','Parrillero o choricero en venta callejera'),
	 ('91113','Vendedor ambulante de refrescos y bebidas'),
	 ('91114','Vendedor ambulante de helados'),
	 ('91115','Caramelero o garrapiñero'),
	 ('91119','Vendedor ambulante de productos comestibles n.c.b.o.e.'),
	 ('91121','Vendedor o repartidor de periódicos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('91129','Vendedor ambulante de productos no comestibles'),
	 ('91131','Vendedor a domicilio'),
	 ('91132','Vendedor de ofertas por teléfono'),
	 ('91201','Limpiabotas o lustrabotas'),
	 ('91202','Pegador de carteles o pegatinero'),
	 ('91203','Acomodador de autos'),
	 ('91311','Mucama doméstica o limpiadora en hogares'),
	 ('91312','Cocinera doméstica o sirviente de cocina'),
	 ('91319','Empleada o criada doméstica'),
	 ('91320','Capataz de limpiadores de oficinas, hoteles y otros establecimientos');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('91321','Camarero de hotelería'),
	 ('91322','Lavaplatos'),
	 ('91323','Limpiador, mucama o auxiliar de servicio en establecimientos'),
	 ('91324','Peón de limpieza en aeronaves o autobuses'),
	 ('91325','Fumigador'),
	 ('91331','Lavandero a mano'),
	 ('91332','Planchador a mano'),
	 ('91333','Clasificador de ropa'),
	 ('91334','Almidonador de lavandería'),
	 ('91411','Conserje de edificio');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('91412','Empleado de limpieza de edificio de apartamentos'),
	 ('91413','Casero'),
	 ('91414','Sacristán'),
	 ('91420','Capataz de lavadores de vehículos, ventanas y afines'),
	 ('91421','Limpiador de vehículos'),
	 ('91422','Limpiador de ventanas'),
	 ('91511','Mensajero o mandadero'),
	 ('91512','Mozo de cordel'),
	 ('91513','Maletero de hotel o botones'),
	 ('91514','Ascensorista');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('91515','Caddie o porteador de palos de golf'),
	 ('91516','Alcanzapelotas'),
	 ('91517','Cuidador de perros'),
	 ('91521','Conserje o portero de hotel'),
	 ('91522','Acomodador en cines o teatros'),
	 ('91523','Guardián de parques y jardines públicos'),
	 ('91524','Guardián de galería de arte o museo'),
	 ('91525','Guardián de estacionamiento'),
	 ('91526','Guardián de guardarropa o vestuario'),
	 ('91527','Sereno o vigilante nocturno');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('91528','Portero de edificios'),
	 ('91529','Guardián o vigilante n.c.b.o.e.'),
	 ('91531','Lector de medidores y tomaconsumos'),
	 ('91532','Recolector de monedas de aparatos de venta automática'),
	 ('91610','Capataz de recolectores de basura'),
	 ('91611','Basurero o recolector de basura'),
	 ('91612','Hurgador de basura'),
	 ('91613','Botellero, juntapapeles y otros materiales reciclables'),
	 ('91620','Capataz de barrenderos'),
	 ('91621','Barrendero de calles o rastrillero de parques');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('91622','Barrendero de lugares públicos'),
	 ('91623','Camposantero'),
	 ('91711','Prostituta o meretriz'),
	 ('91721','Copera'),
	 ('92110','Capataz de peones de labranza y agropecuarios'),
	 ('92111','Peón de labranza agrícola'),
	 ('92112','Peón de labranza pecuario'),
	 ('92113','Recolector de frutos'),
	 ('92114','Arriero o tropero'),
	 ('92115','Peón agropecuario estacional o temporero');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('92116','Peón de stud'),
	 ('92119','Peón agropecuario n.c.b.o.e.'),
	 ('92120','Capataz de peones forestales'),
	 ('92121','Peón forestal'),
	 ('92130','Capataz de peones de la pesca, la caza y la trampa'),
	 ('92131','Recolector de algas marinas o moluscos'),
	 ('92132','Peón pesquero'),
	 ('92133','Peón cazador o trampero'),
	 ('93111','Peón de minas y canteras'),
	 ('93112','Peón de arenera');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('93121','Peón de construcción de carreteras'),
	 ('93122','Cavador de zanjas y acequias'),
	 ('93123','Peón de mantenimiento de carreteras'),
	 ('93124','Peón de mantenimiento ferroviario'),
	 ('93131','Peón de construcción de edificios'),
	 ('93132','Peón de demolición'),
	 ('93211','Peón de operaciones de montaje manual'),
	 ('93221','Embalador, embolsador o empaquetador a mano'),
	 ('93222','Embotellador manual'),
	 ('93223','Envasador a mano');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('93224','Etiquetador a mano'),
	 ('93225','Lavador a mano en taller de fabricación'),
	 ('93229','Peón de industria manufacturera'),
	 ('93311','Conductor de vehículo a pedales'),
	 ('93321','Conductor de vehículos o máquinas de tracción animal'),
	 ('93330','Capataz de peones de carga'),
	 ('93331','Peón de carga en buques, trenes o aviones'),
	 ('93332','Cargador en camiones'),
	 ('93333','Peón de carga en empresas de mudanza'),
	 ('93334','Peón portuario, guinchero o estibador manual');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('93335','Reponedor de grandes almacenes o tiendas'),
	 ('93339','Balancero'),
	 ('01111','Teniente General, General o Coronel del Ejército'),
	 ('01112','Teniente Coronel del Ejército'),
	 ('01113','Mayor del Ejército'),
	 ('01114','Capitán del Ejército'),
	 ('01115','Teniente 1° del Ejército'),
	 ('01116','Teniente 2° del Ejército'),
	 ('01117','Alférez del Ejército'),
	 ('01121','Vice Almirante, Contra Almirante o Capitán de Navío');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('01122','Capitán de Fragata'),
	 ('01123','Capitán de Corbeta'),
	 ('01124','Teniente de Navío'),
	 ('01125','Alférez de Navío'),
	 ('01126','Alférez de Fragata'),
	 ('01127','Guardia Marina'),
	 ('01131','Brigadier General, Brigadier o Coronel de la Fuerza Aérea'),
	 ('01132','Teniente Coronel de la Fuerza Aérea'),
	 ('01133','Mayor de la Fuerza Aérea'),
	 ('01134','Capitán de la Fuerza Aérea');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('01135','Teniente 1° de la Fuerza Aérea'),
	 ('01136','Teniente 2° de la Fuerza Aérea'),
	 ('01137','Alférez de la Fuerza Aérea'),
	 ('01199','Oficiales de las Fuerzas Armadas, n.c.b.o.e.'),
	 ('01211','Sub-Oficial Mayor del Ejército'),
	 ('01212','Sargento 1° del Ejército'),
	 ('01213','Sargento'),
	 ('01214','Cabo de 1a. del Ejército'),
	 ('01215','Cabo de 2a. del Ejército'),
	 ('01216','Soldado de 1a. del Ejército');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('01217','Soldado de 2a. del Ejército'),
	 ('01221','Sub-Oficial de Cargo'),
	 ('01222','Sub-Oficial de 1a.'),
	 ('01223','Sub-Oficial de 2a.'),
	 ('01224','Cabo de 1a. de la Armada'),
	 ('01225','Cabo de 2a. de la Armada'),
	 ('01226','Marinero de 1a.'),
	 ('01227','Marinero de 2a.'),
	 ('01231','Sub-Oficial Mayor de la Fuerza Aérea'),
	 ('01232','Sargento 1° de la Fuerza Aérea');
INSERT INTO public.ocupaciones (ocupacion_codigo,descripcion) VALUES
	 ('01233','Cabo de 1a. de la Fuerza Aérea'),
	 ('01234','Cabo de 2a. de la Fuerza Aérea'),
	 ('01235','Soldado de 1a. de la Fuerza Aérea'),
	 ('01236','Soldado de 2a. de la Fuerza Aérea'),
	 ('01299','Personal Subalterno de las Fuerzas Armadas, n.c.b.o.e'),
	 ('X1111','Persona en busca de su primer empleo'),
	 ('X2111','Trabajador que ha declarado ocupación no identificable o insuficientemente descrita'),
	 ('X3111','Trabajadores que no han declarado ninguna ocupación');
