INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('AD','Principality of Andorra','.ad','376                 ','EU'),
	 ('AE','United Arab Emirates','.ae','971                 ','AS'),
	 ('AF','Islamic Republic of Afghanistan','.af','93                  ','AS'),
	 ('AG','Antigua and Barbuda','.ag','+1-268              ','NA'),
	 ('AI','Anguilla','.ai','+1-264              ','NA'),
	 ('AL','Republic of Albania','.al','355                 ','EU'),
	 ('AM','Republic of Armenia','.am','374                 ','AS'),
	 ('AO','Republic of Angola','.ao','244                 ','AF'),
	 ('AQ','Antarctica','.aq',NULL,'AN'),
	 ('AR','Argentine Republic','.ar','54                  ','SA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('AS','American Samoa, Territory of','.as','+1-684              ','OC'),
	 ('AT','Republic of Austria','.at','43                  ','EU'),
	 ('AU','Commonwealth of Australia','.au','61                  ','OC'),
	 ('AW','Aruba','.aw','297                 ','NA'),
	 ('AX','Ahvenanmaan Laeaeni','.ax','+358-18             ','EU'),
	 ('AZ','Republic of Azerbaijan','.az','994                 ','AS'),
	 ('BA','Bosnia and Herzegovina','.ba','387                 ','EU'),
	 ('BB','Barbados','.bb','+1-246              ','NA'),
	 ('BD','People''s Republic of Bangladesh','.bd','880                 ','AS'),
	 ('BE','Kingdom of Belgium','.be','32                  ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('BF','Burkina Faso','.bf','226                 ','AF'),
	 ('BG','Republic of Bulgaria','.bg','359                 ','EU'),
	 ('BH','Kingdom of Bahrain','.bh','973                 ','AS'),
	 ('BI','Republic of Burundi','.bi','257                 ','AF'),
	 ('BJ','Republic of Benin','.bj','229                 ','AF'),
	 ('BL','Saint-Barthelemy','.gp','590                 ','NA'),
	 ('BM','Bermuda','.bm','+1-441              ','NA'),
	 ('BN','Negara Brunei Darussalam','.bn','673                 ','AS'),
	 ('BO','Plurinational State of Bolivia','.bo','591                 ','SA'),
	 ('BQ','Bonaire, Saint Eustatius and Saba','.bq','599                 ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('BR','Federative Republic of Brazil','.br','55                  ','SA'),
	 ('BS','Commonwealth of The Bahamas','.bs','+1-242              ','NA'),
	 ('BT','Kingdom of Bhutan','.bt','975                 ','AS'),
	 ('BV','Bouvet Island','.bv',NULL,'AN'),
	 ('BW','Republic of Botswana','.bw','267                 ','AF'),
	 ('BY','Republic of Belarus','.by','375                 ','EU'),
	 ('BZ','Belize','.bz','501                 ','NA'),
	 ('CA','Canada','.ca','1                   ','NA'),
	 ('CC','Territory of Cocos (Keeling) Islands','.cc','61                  ','AS'),
	 ('CD','Democratic Republic of the Congo','.cd','243                 ','AF');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('CF','Central African Republic','.cf','236                 ','AF'),
	 ('CG','Republic of the Congo','.cg','242                 ','AF'),
	 ('CH','Swiss Confederation','.ch','41                  ','EU'),
	 ('CI','Republic of Cote d''Ivoire','.ci','225                 ','AF'),
	 ('CK','Cook Islands','.ck','682                 ','OC'),
	 ('CL','Republic of Chile','.cl','56                  ','SA'),
	 ('CM','Republic of Cameroon','.cm','237                 ','AF'),
	 ('CN','People''s Republic of China','.cn','86                  ','AS'),
	 ('CO','Republic of Colombia','.co','57                  ','SA'),
	 ('CR','Republic of Costa Rica','.cr','506                 ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('CU','Republic of Cuba','.cu','53                  ','NA'),
	 ('CV','Republic of Cape Verde','.cv','238                 ','AF'),
	 ('CW','Land Curacao','.cw','599                 ','NA'),
	 ('CX','Territory of Christmas Island','.cx','61                  ','AS'),
	 ('CY','Republic of Cyprus','.cy','357                 ','EU'),
	 ('CZ','Czech Republic','.cz','420                 ','EU'),
	 ('DE','Federal Republic of Germany','.de','49                  ','EU'),
	 ('DJ','Republic of Djibouti','.dj','253                 ','AF'),
	 ('DK','Kingdom of Denmark','.dk','45                  ','EU'),
	 ('DM','Dominica','.dm','+1-767              ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('DO','Dominican Republic','.do','+1-809 and 1-829    ','NA'),
	 ('DZ','People''s Democratic Republic of Algeria','.dz','213                 ','AF'),
	 ('EC','Republic of Ecuador','.ec','593                 ','SA'),
	 ('EE','Republic of Estonia','.ee','372                 ','EU'),
	 ('EG','Arab Republic of Egypt','.eg','20                  ','AF'),
	 ('EH','Western Sahara','.eh','212                 ','AF'),
	 ('ER','State of Eritrea','.er','291                 ','AF'),
	 ('ES','Kingdom of Spain','.es','34                  ','EU'),
	 ('ET','Federal Democratic Republic of Ethiopia','.et','251                 ','AF'),
	 ('FI','Republic of Finland','.fi','358                 ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('FJ','Republic of Fiji','.fj','679                 ','OC'),
	 ('FK','Falkland Islands (Islas Malvinas)','.fk','500                 ','SA'),
	 ('FM','Federated States of Micronesia','.fm','691                 ','OC'),
	 ('FO','Faroe Islands','.fo','298                 ','EU'),
	 ('FR','Republic of France','.fr','33                  ','EU'),
	 ('GA','Gabonese Republic','.ga','241                 ','AF'),
	 ('GB','United Kingdom of Great Britain and Northern Ireland','.uk','44                  ','EU'),
	 ('GD','Grenada','.gd','+1-473              ','NA'),
	 ('GE','Georgia','.ge','995                 ','AS'),
	 ('GF','Guyane','.gf','594                 ','SA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('GG','Bailiwick of Guernsey','.gg','+44-1481            ','EU'),
	 ('GH','Republic of Ghana','.gh','233                 ','AF'),
	 ('GI','Gibraltar','.gi','350                 ','EU'),
	 ('GL','Greenland','.gl','299                 ','NA'),
	 ('GM','Gambia','.gm','220                 ','AF'),
	 ('GN','Republic of Guinea','.gn','224                 ','AF'),
	 ('GP','Guadeloupe','.gp','590                 ','NA'),
	 ('GQ','Republic of Equatorial Guinea','.gq','240                 ','AF'),
	 ('GR','Hellenic Republic','.gr','30                  ','EU'),
	 ('GS','South Georgia and the South Sandwich Islands','.gs',NULL,'AN');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('GT','Republic of Guatemala','.gt','502                 ','NA'),
	 ('GU','Guam','.gu','+1-671              ','OC'),
	 ('GW','Republic of Guinea-Bissau','.gw','245                 ','AF'),
	 ('GY','Co-operative Republic of Guyana','.gy','592                 ','SA'),
	 ('HK','Hong Kong Special Administrative Region','.hk','852                 ','AS'),
	 ('HM','Territory of Heard Island and McDonald Islands','.hm',NULL,'AN'),
	 ('HN','Republic of Honduras','.hn','504                 ','NA'),
	 ('HR','Republic of Croatia','.hr','385                 ','EU'),
	 ('HT','Republic of Haiti','.ht','509                 ','NA'),
	 ('HU','Hungary','.hu','36                  ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('ID','Republic of Indonesia','.id','62                  ','AS'),
	 ('IE','Ireland','.ie','353                 ','EU'),
	 ('IL','State of Israel','.il','972                 ','AS'),
	 ('IM','Isle of Man','.im','+44-1624            ','EU'),
	 ('IN','Republic of India','.in','91                  ','AS'),
	 ('IO','British Indian Ocean Territory','.io','246                 ','AS'),
	 ('IQ','Republic of Iraq','.iq','964                 ','AS'),
	 ('IR','Islamic Republic of Iran','.ir','98                  ','AS'),
	 ('IS','Republic of Iceland','.is','354                 ','EU'),
	 ('IT','Repubblica Italiana','.it','39                  ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('JE','Bailiwick of Jersey','.je','+44-1534            ','EU'),
	 ('JM','Jamaica','.jm','+1-876              ','NA'),
	 ('JO','Hashemite Kingdom of Jordan','.jo','962                 ','AS'),
	 ('JP','Japan','.jp','81                  ','AS'),
	 ('KE','Republic of Kenya','.ke','254                 ','AF'),
	 ('KG','Kyrgyz Republic','.kg','996                 ','AS'),
	 ('KH','Kingdom of Cambodia','.kh','855                 ','AS'),
	 ('KI','Republic of Kiribati','.ki','686                 ','OC'),
	 ('KM','Union of the Comoros','.km','269                 ','AF'),
	 ('KN','Federation of Saint Kitts and Nevis','.kn','+1-869              ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('KP','Democratic People''s Republic of Korea','.kp','850                 ','AS'),
	 ('KR','Republic of Korea','.kr','82                  ','AS'),
	 ('KW','State of Kuwait','.kw','965                 ','AS'),
	 ('KY','Cayman Islands','.ky','+1-345              ','NA'),
	 ('KZ','Republic of Kazakhstan','.kz','7                   ','AS'),
	 ('LA','Lao People''s Democratic Republic','.la','856                 ','AS'),
	 ('LB','Republic of Lebanon','.lb','961                 ','AS'),
	 ('LC','Saint Lucia','.lc','+1-758              ','NA'),
	 ('LI','Principality of Liechtenstein','.li','423                 ','EU'),
	 ('LK','Democratic Socialist Republic of Sri Lanka','.lk','94                  ','AS');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('LR','Republic of Liberia','.lr','231                 ','AF'),
	 ('LS','Kingdom of Lesotho','.ls','266                 ','AF'),
	 ('LT','Republic of Lithuania','.lt','370                 ','EU'),
	 ('LU','Grand Duchy of Luxembourg','.lu','352                 ','EU'),
	 ('LV','Republic of Latvia','.lv','371                 ','EU'),
	 ('LY','Libya','.ly','218                 ','AF'),
	 ('MA','Kingdom of Morocco','.ma','212                 ','AF'),
	 ('MC','Principality of Monaco','.mc','377                 ','EU'),
	 ('MD','Republic of Moldova','.md','373                 ','EU'),
	 ('ME','Montenegro','.me','382                 ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('MF','Saint-Martin','.gp','590                 ','NA'),
	 ('MG','Republic of Madagascar','.mg','261                 ','AF'),
	 ('MH','Republic of the Marshall Islands','.mh','692                 ','OC'),
	 ('MK','Republic of Macedonia','.mk','389                 ','EU'),
	 ('ML','Republic of Mali','.ml','223                 ','AF'),
	 ('MM','Union of Burma','.mm','95                  ','AS'),
	 ('MN','Mongolia','.mn','976                 ','AS'),
	 ('MO','Macau Special Administrative Region','.mo','853                 ','AS'),
	 ('MP','Commonwealth of the Northern Mariana Islands','.mp','+1-670              ','OC'),
	 ('MQ','Martinique','.mq','596                 ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('MR','Islamic Republic of Mauritania','.mr','222                 ','AF'),
	 ('MS','Montserrat','.ms','+1-664              ','NA'),
	 ('MT','Republic of Malta','.mt','356                 ','EU'),
	 ('MU','Republic of Mauritius','.mu','230                 ','AF'),
	 ('MV','Republic of Maldives','.mv','960                 ','AS'),
	 ('MW','Republic of Malawi','.mw','265                 ','AF'),
	 ('MX','Mexico','.mx','52                  ','NA'),
	 ('MY','Malaysia','.my','60                  ','AS'),
	 ('MZ','Republic of Mozambique','.mz','258                 ','AF'),
	 ('NA','Republic of Namibia','.na','264                 ','AF');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('NC','Nouvelle-Caledonie','.nc','687                 ','OC'),
	 ('NE','Republic of Niger','.ne','227                 ','AF'),
	 ('NF','Territory of Norfolk Island','.nf','672                 ','OC'),
	 ('NG','Federal Republic of Nigeria','.ng','234                 ','AF'),
	 ('NI','Republic of Nicaragua','.ni','505                 ','NA'),
	 ('NL','Kingdom of the Netherlands','.nl','31                  ','EU'),
	 ('NO','Kingdom of Norway','.no','47                  ','EU'),
	 ('NP','Federal Democratic Republic of Nepal','.np','977                 ','AS'),
	 ('NR','Nauru','.nr','674                 ','OC'),
	 ('NU','Niue','.nu','683                 ','OC');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('NZ','New Zealand','.nz','64                  ','OC'),
	 ('OM','Sultanate of Oman','.om','968                 ','AS'),
	 ('PA','Republic of Panama','.pa','507                 ','NA'),
	 ('PE','Republic of Peru','.pe','51                  ','SA'),
	 ('PF','Polynesie Francaise','.pf','689                 ','OC'),
	 ('PG','Independent State of Papua New Guinea','.pg','675                 ','OC'),
	 ('PH','Republic of the Philippines','.ph','63                  ','AS'),
	 ('PK','Islamic Republic of Pakistan','.pk','92                  ','AS'),
	 ('PL','Republic of Poland','.pl','48                  ','EU'),
	 ('PM','Saint-Pierre et Miquelon','.pm','508                 ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('PN','Henderson, Ducie and Oeno Islands Pitcairn','.pn','870                 ','OC'),
	 ('PR','Puerto Rico','.pr','+1-787 and 1-939    ','NA'),
	 ('PS','Palestine','.ps','970                 ','AS'),
	 ('PT','Portuguese Republic','.pt','351                 ','EU'),
	 ('PW','Republic of Palau','.pw','680                 ','OC'),
	 ('PY','Republic of Paraguay','.py','595                 ','SA'),
	 ('QA','State of Qatar','.qa','974                 ','AS'),
	 ('RE','Reunion','.re','262                 ','AF'),
	 ('RO','Romania','.ro','40                  ','EU'),
	 ('RS','Serbia','.rs','381                 ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('RU','Russian Federation','.ru','7                   ','EU'),
	 ('RW','Republic of Rwanda','.rw','250                 ','AF'),
	 ('SA','Kingdom of Saudi Arabia','.sa','966                 ','AS'),
	 ('SB','Solomon Islands','.sb','677                 ','OC'),
	 ('SC','Republic of Seychelles','.sc','248                 ','AF'),
	 ('SD','Republic of the Sudan','.sd','249                 ','AF'),
	 ('SE','Kingdom of Sweden','.se','46                  ','EU'),
	 ('SG','Republic of Singapore','.sg','65                  ','AS'),
	 ('SH','Ascension, and Tristan da Cunha Saint Helena','.sh','290                 ','AF'),
	 ('SI','Republic of Slovenia','.si','386                 ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('SJ','Svalbard and Jan Mayen','.sj','47                  ','EU'),
	 ('SK','Slovak Republic','.sk','421                 ','EU'),
	 ('SL','Republic of Sierra Leone','.sl','232                 ','AF'),
	 ('SM','Repubblica di San Marino','.sm','378                 ','EU'),
	 ('SN','Republic of Senegal','.sn','221                 ','AF'),
	 ('SO','Somalia','.so','252                 ','AF'),
	 ('SR','Republic of Suriname','.sr','597                 ','SA'),
	 ('SS','South Sudan',NULL,'211                 ','AF'),
	 ('ST','Sao Tome and Principe','.st','239                 ','AF'),
	 ('SV','Republic of El Salvador','.sv','503                 ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('SX','Land Sint Maarten','.sx','599                 ','NA'),
	 ('SY','Syrian Arab Republic','.sy','963                 ','AS'),
	 ('SZ','Kingdom of Swaziland','.sz','268                 ','AF'),
	 ('TC','Turks and Caicos Islands','.tc','+1-649              ','NA'),
	 ('TD','Republic of Chad','.td','235                 ','AF'),
	 ('TF','Territory of the French Southern and Antarctic Lands','.tf',NULL,'AN'),
	 ('TG','Togolese Republic','.tg','228                 ','AF'),
	 ('TH','Kingdom of Thailand','.th','66                  ','AS'),
	 ('TJ','Republic of Tajikistan','.tj','992                 ','AS'),
	 ('TK','Tokelau','.tk','690                 ','OC');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('TL','Democratic Republic of Timor-Leste','.tl','670                 ','OC'),
	 ('TM','Turkmenistan','.tm','993                 ','AS'),
	 ('TN','Tunisian Republic','.tn','216                 ','AF'),
	 ('TO','Kingdom of Tonga','.to','676                 ','OC'),
	 ('TR','Republic of Turkey','.tr','90                  ','AS'),
	 ('TT','Republic of Trinidad and Tobago','.tt','+1-868              ','NA'),
	 ('TV','Tuvalu','.tv','688                 ','OC'),
	 ('TW','Taiwan','.tw','886                 ','AS'),
	 ('TZ','United Republic of Tanzania','.tz','255                 ','AF'),
	 ('UA','Ukraine','.ua','380                 ','EU');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('UG','Republic of Uganda','.ug','256                 ','AF'),
	 ('UM','United States Minor Outlying Islands','.um','1                   ','OC'),
	 ('US','United States','.us','1                   ','NA'),
	 ('UY','Oriental Republic of Uruguay','.uy','598                 ','SA'),
	 ('UZ','Republic of Uzbekistan','.uz','998                 ','AS'),
	 ('VA','State of the Vatican City','.va','379                 ','EU'),
	 ('VC','Saint Vincent and the Grenadines','.vc','+1-784              ','NA'),
	 ('VE','Bolivarian Republic of Venezuela','.ve','58                  ','SA'),
	 ('VG','British Virgin Islands','.vg','+1-284              ','NA'),
	 ('VI','Virgin Islands of the United States','.vi','+1-340              ','NA');
INSERT INTO public.paises (pais_codigo,nombre,tld,prefijo_telefonico,continente_codigo) VALUES
	 ('VN','Socialist Republic of Vietnam','.vn','84                  ','AS'),
	 ('VU','Republic of Vanuatu','.vu','678                 ','OC'),
	 ('WF','Wallis et Futuna','.wf','681                 ','OC'),
	 ('WS','Independent State of Samoa','.ws','685                 ','OC'),
	 ('XK','Republic of Kosovo',NULL,NULL,'EU'),
	 ('YE','Republic of Yemen','.ye','967                 ','AS'),
	 ('YT','Mayotte','.yt','262                 ','AF'),
	 ('ZA','Republic of South Africa','.za','27                  ','AF'),
	 ('ZM','Republic of Zambia','.zm','260                 ','AF'),
	 ('ZW','Republic of Zimbabwe','.zw','263                 ','AF');
